import { QuestionV2 } from "@/lib/quiz-types";

const csc311Chapter1: QuestionV2[] = [
  {
    id: "csc311_001",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Adoption of ______ has increased in most countries, but at the same time, the rate of successful adoption and operation varies from country to country.",
    options: [
      "e-commerce",
      "e-government",
      "digital policy",
      "information mapping",
    ],
    correctAnswer: 1,
    explanation:
      "Over the last decades, governments have tried to take advantage of ICT to improve government operations and communication with citizens, leading to an increased adoption of e-government.",
  },
  {
    id: "csc311_002",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "On JUL 1, 1642, Blaise Pascal invented the ______ so figures could be added to provide information.",
    options: [
      "punch card system",
      "mainframe computer",
      "mechanical calculator",
      "abacus tabulator",
    ],
    correctAnswer: 2,
    explanation:
      "Blaise Pascal, a French mathematician and philosopher, invented the mechanical calculator in 1642.",
  },
  {
    id: "csc311_003",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Herman Hollerith created a ______ system to tabulate data for the 1890 census.",
    options: [
      "mechanical calculator",
      "punch card",
      "binary tree",
      "random access",
    ],
    correctAnswer: 1,
    explanation:
      "Herman Hollerith created a punch card system to tabulate data for the 1890 census.",
  },
  {
    id: "csc311_004",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Hollerith later used the company to provide data processing equipment evolving into Microsoft.",
    options: ["Maybe", "True", "I don't know", "False"],
    correctAnswer: 3,
    explanation:
      "False. Hollerith later used the company to provide data processing equipment evolving into International Business Machines (IBM).",
  },
  {
    id: "csc311_005",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "In 1952, IBM created a punch card system that allowed ______ to read and interpret data from computers by reading hole punchers.",
    options: ["personal computers", "mainframes", "tabulators", "calculators"],
    correctAnswer: 1,
    explanation:
      "May 21, 1952: Punch Cards - IBM Created a punch card system- allowed mainframes to read and interpret data.",
  },
  {
    id: "csc311_006",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "By the mid-1960s, accounting systems were fairly effective in supplying descriptive information but lacked ______.",
    options: ["accuracy", "capacity", "security", "flexibility"],
    correctAnswer: 1,
    explanation:
      "Mid1960's accounting systems were fairly effective in supplying descriptive information's but lacked capacity.",
  },
  {
    id: "csc311_007",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "In Sep 1970, Colleges and Business schools created a full four-year program designed to study ______.",
    options: [
      "computer engineering",
      "information systems",
      "data processing",
      "network topology",
    ],
    correctAnswer: 1,
    explanation:
      "Sep 7, 1970: Four year program - Colleges and Business schools created a full four-year program designed to study information systems.",
  },
  {
    id: "csc311_008",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The first cell phone call was made in 1990.",
    options: ["True", "I don't know", "False", "Maybe"],
    correctAnswer: 2,
    explanation:
      "False. The history timeline places the first cell phone call in the 1970 era.",
  },
  {
    id: "csc311_009",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "In 1980, using Word Processors and Spreadsheets made departments less dependent on the ______.",
    options: [
      "mainframe system",
      "IT department",
      "management team",
      "Internet",
    ],
    correctAnswer: 1,
    explanation:
      "Using Word Processors and Spreadsheets made departments less depend on the IT department.",
  },
  {
    id: "csc311_010",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "By Jan 1, 1990, Wide Area Networks (WANs) became ______.",
    options: [
      "obsolete",
      "corporate standards",
      "decentralized systems",
      "global enterprises",
    ],
    correctAnswer: 1,
    explanation:
      "Jan 1, 1990: Wide Area Networks (WANs) become corporate standards.",
  },
  {
    id: "csc311_011",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "______ are raw facts that simply exist and have no significance beyond their existence.",
    options: ["Knowledge", "Processes", "Information", "Data"],
    correctAnswer: 3,
    explanation:
      "Data is raw. It simply exists and has no significance beyond its existence (in and of itself).",
  },
  {
    id: "csc311_012",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Information is a collection of facts organized in such a way that they have ______ beyond the value of the facts themselves.",
    options: [
      "additional value",
      "technological meaning",
      "systematic hierarchy",
      "raw data",
    ],
    correctAnswer: 0,
    explanation:
      "Information: Collection of facts organized in such a way that they have additional value beyond the value of the facts themselves.",
  },
  {
    id: "csc311_013",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A ______ is a set of logically related tasks performed to achieve a defined outcome.",
    options: ["System", "Process", "Knowledge base", "Database"],
    correctAnswer: 1,
    explanation:
      "Process: Set of logically related tasks performed to achieve a defined outcome.",
  },
  {
    id: "csc311_014",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "______ is an awareness and understanding of a set of information.",
    options: ["Knowledge", "Data", "Process", "System modeling"],
    correctAnswer: 0,
    explanation:
      "Knowledge: Awareness and understanding of a set of information.",
  },
  {
    id: "csc311_015",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "One of the key properties of information is its ______, which is a key component of any modern scientific research.",
    options: [
      "temporariness",
      "subjectiveness",
      "objectiveness",
      "random access",
    ],
    correctAnswer: 2,
    explanation:
      "Objective: One of the key properties of information is its objectiveness. Objective information is a key component of any modern scientific research.",
  },
  {
    id: "csc311_016",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Information is ______ with every update in the database.",
    options: ["subjective", "objective", "temporary", "permanent"],
    correctAnswer: 2,
    explanation:
      "Temporary: Information is temporary with every update in the database.",
  },
  {
    id: "csc311_017",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The decimal system and binary system are two ways of representing information.",
    options: ["False", "I don't know", "Maybe", "True"],
    correctAnswer: 3,
    explanation:
      "True. Decimal system and binary system are two ways of representing information.",
  },
  {
    id: "csc311_018",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "In database management systems, administrative information stored in files such as index files and data dictionaries is known as ______.",
    options: [
      "alphanumeric data",
      "metadata",
      "hypertext",
      "system parameters",
    ],
    correctAnswer: 1,
    explanation:
      "In database management systems, other files, such as index files and data dictionaries, store administrative information, known as metadata.",
  },
  {
    id: "csc311_019",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Moving images or pictures are represented by ______ data.",
    options: ["Image", "Alphanumeric", "Audio", "Video"],
    correctAnswer: 3,
    explanation: "Video data represents moving images or pictures.",
  },
  {
    id: "csc311_020",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Sound, noise or tones are represented by ______ data.",
    options: ["Audio", "Video", "Alphanumeric", "Image"],
    correctAnswer: 0,
    explanation: "Audio data represents sound, noise or tones.",
  },
  {
    id: "csc311_021",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The simplest way of organizing information is through a ______ model, in which data is structured one after another.",
    options: ["binary tree", "random access", "linear", "hypertext"],
    correctAnswer: 2,
    explanation:
      "The simplest way of organizing information is through linear model. In this form, data is structured one after another, for example, in magnetic tapes.",
  },
  {
    id: "csc311_022",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "In a ______, data is arranged in an inverted tree format where it assumes two values.",
    options: [
      "hierarchy model",
      "binary tree model",
      "network topology",
      "linear model",
    ],
    correctAnswer: 1,
    explanation:
      "In a binary tree model, data is arranged in an inverted tree format where it assumes two values.",
  },
  {
    id: "csc311_023",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The UNIX operating system uses the ______ model for its file system.",
    options: ["hypertext", "binary tree", "linear", "hierarchy"],
    correctAnswer: 3,
    explanation:
      "The hierarchy model is derived from a binary tree model... for example in the UNIX operating system this model is used for its file system.",
  },
  {
    id: "csc311_024",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The World Wide Web is an example of the ______ model of organizing information.",
    options: ["hierarchy", "hypertext", "random access", "networking"],
    correctAnswer: 1,
    explanation:
      "The hypertext model is another way of organizing information; World Wide Web is an example of this model.",
  },
  {
    id: "csc311_025",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The random access model is used for optimum utilization of available computer storage space.",
    options: ["I don't know", "Maybe", "True", "False"],
    correctAnswer: 2,
    explanation:
      "True. Random access model is another way of organizing information. This model is used for optimum utilization of available computer storage space.",
  },
  {
    id: "csc311_026",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The layout of all the connected devices, which provides virtual shape or structure to the network, is known as ______.",
    options: [
      "network topology",
      "system boundary",
      "information mapping",
      "IT infrastructure",
    ],
    correctAnswer: 0,
    explanation:
      "The layout of all the connected devices, and it provides virtual shape or structure to the network is known as network topology.",
  },
  {
    id: "csc311_027",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Data back-up is one way through which Information can be made secured.",
    options: ["Maybe", "True", "False", "I don't know"],
    correctAnswer: 1,
    explanation:
      "True. Data back-up is on the way through which Information can be made secured.",
  },
  {
    id: "csc311_028",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The ______ principle states that all information should be grouped into small, manageable units.",
    options: ["Consistency", "Relevance", "Chunking", "Labeling"],
    correctAnswer: 2,
    explanation:
      "Chunking principle: All information should be grouped into small, manageable units.",
  },
  {
    id: "csc311_029",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The ______ principle ensures that information presented should use consistent words, labels, formats, organizations, and sequences.",
    options: ["Integrated graphics", "Consistency", "Relevance", "Chunking"],
    correctAnswer: 1,
    explanation:
      "Consistency principle: Information presented should use consistent words, labels, formats, organizations, and sequences.",
  },
  {
    id: "csc311_030",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Diagrams, tables, pictures, and other visuals should be incorporated as an integral part of the text according to the ______ principle.",
    options: [
      "Integrated graphics",
      "Accessible detail",
      "Labeling",
      "Hierarchy of chunking",
    ],
    correctAnswer: 0,
    explanation:
      "Integrated graphics principle: Diagrams, tables, pictures, and other visuals should be incorporated as an integral part of the text, not as an afterthought.",
  },
  {
    id: "csc311_031",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "In Information Mapping, ______ replaces paragraphs in traditional business writing.",
    options: [
      "Information maps",
      "Information blocks",
      "Information labels",
      "Information chunks",
    ],
    correctAnswer: 1,
    explanation:
      "Information block: One or more sentences, a diagram, a table... This replaces paragraphs in traditional business writing.",
  },
  {
    id: "csc311_032",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "An information map is a collection of relevant information blocks about ______.",
    options: [
      "unrelated concepts",
      "a limited topic",
      "raw data elements",
      "system parameters",
    ],
    correctAnswer: 1,
    explanation:
      "Information map: A collection of relevant information blocks about a limited topic.",
  },
  {
    id: "csc311_033",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The Information Mapping method leverages Moore's Law, which states human memory capacity doubles every 2 years.",
    options: ["I don't know", "False", "Maybe", "True"],
    correctAnswer: 1,
    explanation:
      "False. The method leverages Miller’s Law, which states the number of objects an average human can hold in memory is 7, plus or minus 2.",
  },
  {
    id: "csc311_034",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "According to Miller’s Law, the number of objects an average human can hold in memory is ______.",
    options: [
      "10, plus or minus 1",
      "5, plus or minus 3",
      "7, plus or minus 2",
      "9, plus or minus 2",
    ],
    correctAnswer: 2,
    explanation:
      "Miller’s Law states the number of objects an average human can hold in memory is 7, plus or minus 2.",
  },
  {
    id: "csc311_035",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Based on Miller's Law, the Information Mapping method states a bullet point list should not have more than ______ items.",
    options: ["five", "seven", "nine", "ten"],
    correctAnswer: 2,
    explanation:
      "Thus, the Information Mapping method states a bullet point list should not have more than nine items.",
  },
  {
    id: "csc311_036",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "______ information is error free.",
    options: ["Verifiable", "Accurate", "Reliable", "Complete"],
    correctAnswer: 1,
    explanation:
      "Accurate: How accurate is the information. Accurate information is error free.",
  },
  {
    id: "csc311_037",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "If information contains all the important facts, it is considered ______.",
    options: ["Economical", "Relevant", "Complete", "Simple"],
    correctAnswer: 2,
    explanation:
      "Complete: Does it contain all the important facts? Complete information contains all the important facts.",
  },
  {
    id: "csc311_038",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Information that can be used for a variety of purposes is ______.",
    options: ["Flexible", "Timely", "Reliable", "Accessible"],
    correctAnswer: 0,
    explanation:
      "Flexible: Flexible information can be used for a variety of purposes.",
  },
  {
    id: "csc311_039",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Reliable information is related to how the information was obtained.",
    options: ["False", "I don't know", "True", "Maybe"],
    correctAnswer: 2,
    explanation:
      "True. Reliable: How dependable is the information? It is related to how the information was obtained.",
  },
  {
    id: "csc311_040",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "______ information is pertinent to the question or decision at hand.",
    options: ["Relevant", "Verifiable", "Accurate", "Complete"],
    correctAnswer: 0,
    explanation:
      "Relevant: How pertinent is the information to the question or decision?",
  },
  {
    id: "csc311_041",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Information that is up-to-date is described as ______.",
    options: ["Reliable", "Secure", "Timely", "Economical"],
    correctAnswer: 2,
    explanation: "Timely: How up-to-date is the information?",
  },
  {
    id: "csc311_042",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "If the correctness of the information can be checked, the information is considered ______.",
    options: ["Accurate", "Verifiable", "Reliable", "Accessible"],
    correctAnswer: 1,
    explanation:
      "Verifiable: Can the correctness of the information be checked?",
  },
  {
    id: "csc311_043",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Accessible information should be easily accessible by ______.",
    options: [
      "management only",
      "authorized users",
      "unauthorized users",
      "the IT department",
    ],
    correctAnswer: 1,
    explanation: "Accessible: Should be easily accessible by authorized users.",
  },
  {
    id: "csc311_044",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Secure information should be secure from access by ______.",
    options: [
      "authorized users",
      "knowledge workers",
      "unauthorized users",
      "decision makers",
    ],
    correctAnswer: 2,
    explanation: "Secure: Should be secure from access by unauthorized users.",
  },
  {
    id: "csc311_045",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The value of information is directly linked to how it helps people achieve their ______.",
    options: [
      "technological literacy",
      "database architecture",
      "organizational goal",
      "system parameters",
    ],
    correctAnswer: 2,
    explanation:
      "The value of information is directly linked to how it helps people achieve their organizational goal.",
  },
  {
    id: "csc311_046",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Information flows in a hierarchy and a ______ organisation.",
    options: [
      "randomly accessed",
      "closed system",
      "project based",
      "decentralized",
    ],
    correctAnswer: 2,
    explanation:
      "Information flows in a Hierarchy and project based organisation.",
  },
  {
    id: "csc311_047",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Information mapping builds a clear blueprint of all system information and how it moves.",
    options: ["I don't know", "True", "Maybe", "False"],
    correctAnswer: 1,
    explanation:
      "True. It building a clear blueprint of all system information and how it moves, so the system works smoothly and logically.",
  },
  {
    id: "csc311_048",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "In information mapping, each relevant unit of information should have a ______ to 'advance organize' the content.",
    options: ["graphic", "label", "parameter", "variable"],
    correctAnswer: 1,
    explanation:
      "Labeling principle: Each relevant unit of information should have a label to 'advance organize' the content of the unit for the reader.",
  },
  {
    id: "csc311_049",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Writing at a level of detail that makes the information the reader needs readily accessible follows the ______ principle.",
    options: ["Accessible detail", "Chunking", "Consistency", "Labeling"],
    correctAnswer: 0,
    explanation:
      "Accessible detail principle: Writers should write at a level of detail that makes the information the reader needs readily accessible.",
  },
  {
    id: "csc311_050",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The value of information must also relate to the ______ of its provision, and to the level in the management hierarchy where it is sent and used.",
    options: ["complexity", "frequency", "temporariness", "subjectivity"],
    correctAnswer: 1,
    explanation:
      "The value of information must also relate to the frequency of its provision, and to the level in the management hierarchy where it is sent and used.",
  },
  {
    id: "csc311_051",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A system is a set of elements or components that interact to accomplish a ______.",
    options: [
      "knowledge base",
      "goal or set of objectives",
      "network topology",
      "data processing cycle",
    ],
    correctAnswer: 1,
    explanation:
      "A system is a set of elements or components that interact to accomplish a goal or set of objectives.",
  },
  {
    id: "csc311_052",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "If a component is removed from a system, it will not change the system behaviour.",
    options: ["Maybe", "True", "False", "I don't know"],
    correctAnswer: 2,
    explanation:
      "False. Each component contributes specifically towards the behaviour of the system... If a component is removed, it will change the system behaviour.",
  },
  {
    id: "csc311_053",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The properties and behaviour of system components are inextricably ______.",
    options: ["separated", "inter-mingled", "adaptable", "temporary"],
    correctAnswer: 1,
    explanation:
      "The properties and behaviour of system components are inextricably inter-mingled.",
  },
  {
    id: "csc311_054",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Anti-lock braking systems in cars react depending on road conditions, which demonstrates the ______ feature of a system.",
    options: ["Limitation", "Non-adaptive", "Adaptability", "Permanent"],
    correctAnswer: 2,
    explanation:
      "Adaptability: some systems are adaptive to the exterior environment... For example, anti-lock braking system in car reacts depending on the road conditions.",
  },
  {
    id: "csc311_055",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Every system has pre-defined limits or boundaries within which it operates, which is known as the system's ______.",
    options: ["Topology", "Adaptability", "Limitation", "Feedback"],
    correctAnswer: 2,
    explanation:
      "Limitation: every system has pre-defined limits or boundaries within which it operates.",
  },
  {
    id: "csc311_056",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The activity of gathering and capturing data refers to the system's ______.",
    options: ["Processing mechanisms", "Outputs", "Inputs", "Feedback"],
    correctAnswer: 2,
    explanation: "Inputs: The activity of gathering and capturing data.",
  },
  {
    id: "csc311_057",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Converting or transforming data into useful outputs is done by ______.",
    options: ["Interfaces", "Processing mechanisms", "Outputs", "Inputs"],
    correctAnswer: 1,
    explanation:
      "Processing mechanisms: Converting or transforming data into useful outputs.",
  },
  {
    id: "csc311_058",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The part of the outside world with which the system interacts is called the system’s ______.",
    options: ["boundary", "interface", "environment", "parameter"],
    correctAnswer: 2,
    explanation:
      "The part of the outside world with which the system interacts is called the system’s environment.",
  },
  {
    id: "csc311_059",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A system that has no interaction with the environment is a ______ system.",
    options: ["Closed", "Dynamic", "Simple", "Open"],
    correctAnswer: 0,
    explanation: "Closed: No interaction with the environment.",
  },
  {
    id: "csc311_060",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A ______ system undergoes rapid and constant change over time.",
    options: ["Stable", "Dynamic", "Temporary", "Permanent"],
    correctAnswer: 1,
    explanation: "Dynamic: Undergoes rapid and constant change over time.",
  },
  {
    id: "csc311_061",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Efficiency is a measure of the extent to which a system achieves its goal.",
    options: ["Maybe", "True", "I don't know", "False"],
    correctAnswer: 3,
    explanation:
      "False. Effectiveness is a measure of the extent to which a system achieves its goal. Efficiency is a measure of what is produced divided by what is consumed.",
  },
  {
    id: "csc311_062",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "______ is a measure of what is produced divided by what is consumed.",
    options: ["Effectiveness", "Efficiency", "System Standard", "Feedback"],
    correctAnswer: 1,
    explanation:
      "Efficiency is a measure of what is produced divided by what is consumed.",
  },
  {
    id: "csc311_063",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Effectiveness can be computed by dividing the actual goals achieved by the ______.",
    options: [
      "total produced",
      "total consumed",
      "total stated goals",
      "system parameters",
    ],
    correctAnswer: 2,
    explanation:
      "It can be computed by dividing the goals actually achieved by the total of the stated goal.",
  },
  {
    id: "csc311_064",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A system ______ is a quality or item that can be controlled by the decision maker.",
    options: ["boundary", "parameter", "variable", "model"],
    correctAnswer: 2,
    explanation:
      "A system variable is a quality or item that can be controlled by the decision maker.",
  },
  {
    id: "csc311_065",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A system parameter is a value or quantity that ______.",
    options: [
      "cannot be controlled",
      "can be controlled by the decision maker",
      "measures system efficiency",
      "converts inputs to outputs",
    ],
    correctAnswer: 0,
    explanation:
      "A system parameter is a value or quantity that cannot be controlled by the decision maker.",
  },
  {
    id: "csc311_066",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A model is an ______ that is used to represent reality.",
    options: [
      "exact replica",
      "abstraction or an approximation",
      "unrelated component",
      "open system",
    ],
    correctAnswer: 1,
    explanation:
      "Hence a model can be said to be an abstraction or an approximation that is used to represent reality.",
  },
  {
    id: "csc311_067",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A ______ model provides a verbal description of reality.",
    options: ["physical", "mathematical", "narrative", "schematic"],
    correctAnswer: 2,
    explanation: "Narrative model provides a verbal description of reality.",
  },
  {
    id: "csc311_068",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A tangible representation of reality, often computed, designed or constructed, is a ______ model.",
    options: ["schematic", "narrative", "physical", "mathematical"],
    correctAnswer: 2,
    explanation:
      "A physical model is a tangible representation of reality often computed, designed or constructed.",
  },
  {
    id: "csc311_069",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A graph or chart is an example of a ______ model.",
    options: ["mathematical", "physical", "narrative", "schematic"],
    correctAnswer: 3,
    explanation:
      "A schematic model is a graphic representation of reality such as a graph, chart.",
  },
  {
    id: "csc311_070",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A mathematical model is an ______ representation of reality.",
    options: ["arithmetic", "verbal", "tangible", "graphic"],
    correctAnswer: 0,
    explanation: "A mathematical model is an arithmetic representation.",
  },
  {
    id: "csc311_071",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Information systems are sets of interrelated elements that collect, manipulate, store, and disseminate data.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "True. Information systems are sets of interrelated elements that collect (input), manipulate and Store (process), and disseminate (output) data and information.",
  },
  {
    id: "csc311_072",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The three dimensions of an Information System are People, Organization, and ______.",
    options: ["Technology", "Data", "Software", "Procedures"],
    correctAnswer: 0,
    explanation:
      "Information System is divided into three dimensions which are people, organization and technology.",
  },
  {
    id: "csc311_073",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A business process is a set of ______ for accomplishing work.",
    options: [
      "tangible representations",
      "hardware components",
      "logically related tasks and behaviours",
      "network topologies",
    ],
    correctAnswer: 2,
    explanation:
      "Business processes -> Logically related tasks and behaviours for accomplishing work.",
  },
  {
    id: "csc311_074",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Employee attitudes affect the ability to use systems productively, representing the ______ dimension of IS.",
    options: ["Technology", "Organization", "Procedures", "People"],
    correctAnswer: 3,
    explanation:
      "Under the 'People' dimension: Employee attitudes affect ability to use systems productively.",
  },
  {
    id: "csc311_075",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Computer hardware, software, and networking technology form the ______ of an Information System.",
    options: [
      "Business process",
      "IT Infrastructure",
      "Knowledge base",
      "Schematic model",
    ],
    correctAnswer: 1,
    explanation:
      "IT Infrastructure -> Foundation or platform that information systems built on (Computer hardware, Computer software, Data management, Networking).",
  },
  {
    id: "csc311_076",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The five key components of an IS are Hardware, Software, Data, Procedures, and ______.",
    options: ["Networks", "People", "Management", "Topology"],
    correctAnswer: 1,
    explanation:
      "The Five Components of an IS: Hardware, Software, Data, Procedures, People.",
  },
  {
    id: "csc311_077",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The programs and applications in an IS are known as ______.",
    options: ["Software", "Hardware", "Data", "Procedures"],
    correctAnswer: 0,
    explanation:
      "Software: The programs and applications (system software, application software).",
  },
  {
    id: "csc311_078",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The rules, guidelines, and strategies for using the system are called ______.",
    options: ["Procedures", "Processes", "Software", "Parameters"],
    correctAnswer: 0,
    explanation:
      "Procedures: The rules, guidelines, and strategies for using the system.",
  },
  {
    id: "csc311_079",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "In IS management, Governance determines who makes decisions about IT.",
    options: ["Maybe", "I don't know", "True", "False"],
    correctAnswer: 2,
    explanation:
      "True. Governance: Who makes decisions about IT? (Centralized IT vs. Business Units).",
  },
  {
    id: "csc311_080",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Ensuring IS goals support business goals is known as ______.",
    options: [
      "Strategic Alignment",
      "Value Delivery",
      "Risk Management",
      "System Performance",
    ],
    correctAnswer: 0,
    explanation:
      "Strategic Alignment: Ensuring IS goals support business goals.",
  },
  {
    id: "csc311_081",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Proving the ROI of IT investments is part of ______.",
    options: [
      "Governance",
      "Strategic Alignment",
      "Value Delivery",
      "Risk Management",
    ],
    correctAnswer: 2,
    explanation: "Value Delivery: Proving the ROI of IT investments.",
  },
  {
    id: "csc311_082",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "In a system, a lack of co-ordination among components leads to counterproductive results.",
    options: ["I don't know", "False", "Maybe", "True"],
    correctAnswer: 3,
    explanation:
      "True. In a system, network of components work towards a single objective, if there is lack of co-ordination among components, it leads to counterproductive results.",
  },
  {
    id: "csc311_083",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A college system processes students, professors, and equipment into educated students and meaningful research; in this example, teaching and research act as ______.",
    options: ["Inputs", "Processing mechanisms", "Outputs", "Feedback"],
    correctAnswer: 1,
    explanation:
      "In the college system example, Teaching, Research, and Services are listed as the Processing Mechanism.",
  },
  {
    id: "csc311_084",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "When an ophthalmologist prescribes glasses to fix an eye problem, the patient feeling better serves as ______.",
    options: ["Input", "Process", "Output", "Feedback"],
    correctAnswer: 3,
    explanation: "Example: Patient with glasses is a lot better. (feedback)",
  },
  {
    id: "csc311_085",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "The system components responsible for transformations between inputs and outputs are called ______.",
    options: ["boundaries", "interfaces", "parameters", "models"],
    correctAnswer: 1,
    explanation:
      "The system components responsible for these transformations are called the interfaces.",
  },
  {
    id: "csc311_086",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A system with many elements that are highly related and interconnected is classified as a ______ system.",
    options: ["Simple", "Stable", "Complex", "Dynamic"],
    correctAnswer: 2,
    explanation:
      "Complex: Has many elements that are highly related and interconnected.",
  },
  {
    id: "csc311_087",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "A system that exists for a relatively long period of time is classified as ______.",
    options: ["Temporary", "Stable", "Permanent", "Adaptive"],
    correctAnswer: 2,
    explanation: "Permanent: Exists for a relatively long period of time.",
  },
  {
    id: "csc311_088",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Information system literacy and computer literacy are prerequisites for numerous job opportunities.",
    options: ["False", "True", "Maybe", "I don't know"],
    correctAnswer: 1,
    explanation:
      "True. IS play a fundamental and ever expanding role in all business organizations. Hence, Information system literacy and computer literacy are prerequisites for numerous job opportunities.",
  },
  {
    id: "csc311_089",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "______ stresses knowledge of information technology, equipment and devices, programs, databases, and telecommunications.",
    options: [
      "Information System Literacy",
      "Computer Literacy",
      "Information Mapping",
      "System Modeling",
    ],
    correctAnswer: 1,
    explanation:
      "Computer Literacy: Knowledge of information technology and the way they function, it stresses equipment and devices (hardware), programs and instructions (software), databases and telecommunications.",
  },
  {
    id: "csc311_090",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Evaluating security, compliance, and business continuity falls under ______.",
    options: [
      "Strategic Alignment",
      "Value Delivery",
      "Risk Management",
      "Governance",
    ],
    correctAnswer: 2,
    explanation:
      "Risk Management: Security, compliance, and business continuity.",
  },
  {
    id: "csc311_091",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Business writing is creative writing, meaning the same word should constantly be changed to keep the reader engaged.",
    options: ["False", "Maybe", "I don't know", "True"],
    correctAnswer: 0,
    explanation:
      "False. The Consistency principle states: Business writing is not creative writing; the same word should always be used consistently.",
  },
  {
    id: "csc311_092",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Identifying the source of information and the people that require the information is a key step in ______.",
    options: [
      "Risk Management",
      "Information Mapping",
      "Computer Literacy",
      "Network Topology",
    ],
    correctAnswer: 1,
    explanation:
      "To do Information Mapping, Identification of the source of information is necessary and the people that require the information.",
  },
  {
    id: "csc311_093",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "In Information Mapping, ______ replaces paragraphs in traditional business writing and focuses on a single idea, concept, or step.",
    options: [
      "an information map",
      "a knowledge base",
      "an information block",
      "a schematic model",
    ],
    correctAnswer: 2,
    explanation:
      "Information block: These are small, self-contained units of information that focus on a single idea, concept, step, or fact... This replaces paragraphs in traditional business writing.",
  },
  {
    id: "csc311_094",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Information System ______ is knowledge of how data and information are used by individuals, groups and organizations.",
    options: ["Literacy", "Mapping", "Topology", "Modelling"],
    correctAnswer: 0,
    explanation:
      "Information System Literacy: Knowledge of how data and information are used by individuals, groups and organizations.",
  },
  {
    id: "csc311_095",
    course: "CSC 311",
    chapter: "Chapter 1",
    text: "Information is represented with the help of data, numbers, letters or ______.",
    options: ["symbols", "hypertext", "blocks", "maps"],
    correctAnswer: 0,
    explanation:
      "Information is represented with the help of data, numbers, letters or symbols.",
  },
];

export default csc311Chapter1;
