import { QuestionV2 } from "@/lib/quiz-types";

const csc311Chapter3: QuestionV2[] = [
  {
    id: "csc311_m2l3_001",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Knowing the potential impact of information systems and having the ability to put this knowledge to work can result in a successful personal ______.",
    options: ["vacation", "career", "syllabus", "retirement"],
    correctAnswer: 1,
    explanation:
      "Knowing the potential impact of information systems and having the ability to put this knowledge to work can result in a successful personal career.",
  },
  {
    id: "csc311_m2l3_002",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Information systems can help organizations reach their goals, and help society achieve a higher ______ of life.",
    options: ["quantity", "speed", "quality", "volume"],
    correctAnswer: 2,
    explanation:
      "...organizations that reach their goals, and a society with a higher quality of life.",
  },
  {
    id: "csc311_m2l3_003",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The use of information systems to add value to the organization is strongly influenced by organizational structure, ______, and change.",
    options: ["bureaucracy", "hierarchy", "culture", "models"],
    correctAnswer: 2,
    explanation:
      "The use of information systems to add value to the organization is strongly influenced by orginizational structure, culture and change.",
  },
  {
    id: "csc311_m2l3_004",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "One of the learning objectives is to identify the value-added process in the ______ and describe the role of information systems within them.",
    options: ["supply chain", "corporate ladder", "project team", "data model"],
    correctAnswer: 0,
    explanation:
      "Identify the value-added process in the supply chain and describe the role of information systems within them.",
  },
  {
    id: "csc311_m2l3_005",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Businesses need to be sure that improvements help lower costs, increase profits, improve service, or achieve a ______.",
    options: [
      "continuous improvement",
      "technology diffusion",
      "static environment",
      "competitive advantage",
    ],
    correctAnswer: 3,
    explanation:
      "Because information systems are so important, businesses need to be sure that improvements... help lower costs, increase profits, improve service, or achieve a competitive advantage.",
  },
  {
    id: "csc311_m2l3_006",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "______ between business managers and IS personnel is the key to unlocking the potential of any new or modified system.",
    options: ["Conflict", "Cooperation", "Isolation", "Competition"],
    correctAnswer: 1,
    explanation:
      "Cooperation between business managers and IS personnel is the key to unlocking the potential of any new or modified system.",
  },
  {
    id: "csc311_m2l3_007",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "An organization is a ______ collection of people and various other resources established to accomplish a set of goals.",
    options: ["random", "unstructured", "formal", "informal"],
    correctAnswer: 2,
    explanation:
      "An organization is a formal collection of people and various other resources established to accomplish a set of goals.",
  },
  {
    id: "csc311_m2l3_008",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "An organization has inputs, processing mechanisms, outputs, and ______.",
    options: ["decisions", "environments", "standards", "feedback"],
    correctAnswer: 3,
    explanation: "Has inputs, processing mechanisms, outputs, and feedback.",
  },
  {
    id: "csc311_m2l3_009",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "There is a one-way relationship between organizations and information technology.",
    options: ["I don't know", "False", "Maybe", "True"],
    correctAnswer: 1,
    explanation:
      "False. There is a two-way relationship between organizations and information technology.",
  },
  {
    id: "csc311_m2l3_010",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The complex relationship between organizations and IT is mediated by many factors, including the ______ made by managers.",
    options: ["calculations", "decisions", "models", "interfaces"],
    correctAnswer: 1,
    explanation:
      "This complex two-way relationship is mediated by many factors, not the least of which are the decisions made—or not made—by managers.",
  },
  {
    id: "csc311_m2l3_011",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "According to the technical microeconomic definition, an organization takes resources from the environment and processes them to produce ______.",
    options: ["inputs", "outputs", "culture", "feedback"],
    correctAnswer: 1,
    explanation:
      "An organization is a stable, formal social structure that takes resources from the environment and processes them to produce outputs.",
  },
  {
    id: "csc311_m2l3_012",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The behavioral definition states that an organization is a collection of rights, privileges, obligations, and ______.",
    options: [
      "standard procedures",
      "specialized units",
      "outputs",
      "responsibilities",
    ],
    correctAnswer: 3,
    explanation:
      "A more realistic behavioural definition of an organization is that it is a collection of rights, privileges, obligations, and responsibilities...",
  },
  {
    id: "csc311_m2l3_013",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "In the behavioral view, the organization is delicately balanced over a period of time through conflict and ______.",
    options: [
      "process redesign",
      "continuous improvement",
      "conflict resolution",
      "hierarchical control",
    ],
    correctAnswer: 2,
    explanation:
      "...delicately balanced over a period of time through conflict and conflict resolution.",
  },
  {
    id: "csc311_m2l3_014",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The technical and behavioural definitions of organizations are contradictory and do not complement each other.",
    options: ["True", "Maybe", "False", "I don't know"],
    correctAnswer: 2,
    explanation:
      "False. The technical and behavioural definitions of organizations are not contradictory. Indeed, they complement each other.",
  },
  {
    id: "csc311_m2l3_015",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The behavioural model takes us inside the individual firm to see how technology affects the organization’s ______.",
    options: [
      "supply chain",
      "inner workings",
      "physical hardware",
      "external environment",
    ],
    correctAnswer: 1,
    explanation:
      "...whereas the behavioural model takes us inside the individual firm to see how that technology affects the organization’s inner workings.",
  },
  {
    id: "csc311_m2l3_016",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "All modern organizations are bureaucracies with clear-cut divisions of labour and ______.",
    options: ["unfreezing", "specialization", "conflict", "chance"],
    correctAnswer: 1,
    explanation:
      "All modern organizations have certain characteristics. They are bureaucracies with clear-cut divisions of labour and specialization.",
  },
  {
    id: "csc311_m2l3_017",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Organizations arrange specialists in a hierarchy of ______ in which everyone is accountable to someone.",
    options: ["authority", "projects", "decisions", "systems"],
    correctAnswer: 0,
    explanation:
      "Organizations arrange specialists in a hierarchy of authority in which everyone is accountable to someone...",
  },
  {
    id: "csc311_m2l3_018",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Organizations try to hire and promote employees on the basis of ______ and professionalism, not personal connections.",
    options: [
      "political influence",
      "chance",
      "personal connections",
      "technical qualifications",
    ],
    correctAnswer: 3,
    explanation:
      "Organizations try to hire and promote employees on the basis of technical qualifications and professionalism (not personal connections).",
  },
  {
    id: "csc311_m2l3_019",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The organization is devoted to the principle of efficiency, which involves maximizing output using ______.",
    options: [
      "unlimited resources",
      "external environments",
      "limited inputs",
      "structural politics",
    ],
    correctAnswer: 2,
    explanation:
      "The organization is devoted to the principle of efficiency: maximizing output using limited inputs.",
  },
  {
    id: "csc311_m2l3_020",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Surrounding environments and leadership styles are features of organizations that affect the kinds of information systems used.",
    options: ["Maybe", "True", "I don't know", "False"],
    correctAnswer: 1,
    explanation:
      "True. Other features of organizations include their... Surrounding environments, ... and leadership styles. All of these features affect the kinds of information systems used by organizations.",
  },
  {
    id: "csc311_m2l3_021",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Just prior to entering the process subsystem of an organization, data is considered ______.",
    options: ["external", "internal", "transformed", "refrozen"],
    correctAnswer: 0,
    explanation: "Just prior to entering the subsystem, data is external.",
  },
  {
    id: "csc311_m2l3_022",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "After data enters the process subsystem, it becomes ______.",
    options: ["external", "internal", "processed", "output"],
    correctAnswer: 1,
    explanation: "After it enters the subsystem, it becomes internal.",
  },
  {
    id: "csc311_m2l3_023",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "An organization’s ______ depends on its goals and approach to management, and can affect how it views and uses information systems.",
    options: ["learning", "structure", "diffusion", "infusion"],
    correctAnswer: 1,
    explanation:
      "An organization’s structure depends on its goals and approach to management, and can affect how it views and uses information systems.",
  },
  {
    id: "csc311_m2l3_024",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "In a ______ organizational structure, major department heads report to a president or top-level manager.",
    options: ["Project", "Team", "Traditional", "Virtual"],
    correctAnswer: 2,
    explanation:
      "Traditional organizational structure, also called a hierarchical structure is an organizational structure in which major department heads report to a president or top-level manager.",
  },
  {
    id: "csc311_m2l3_025",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "In a hierarchical organizational structure, those at ______ levels have more power and authority within an organization.",
    options: ["low", "high", "middle", "external"],
    correctAnswer: 1,
    explanation:
      "Hierarchical organizational structure; Series of levels; Those at high levels have more power and authority within an organization.",
  },
  {
    id: "csc311_m2l3_026",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "A ______ organizational structure is centered on major products or services, and can also be temporary teams.",
    options: ["Traditional", "Flat", "Virtual", "Project"],
    correctAnswer: 3,
    explanation:
      "Project organizational structure is a structure centered on major products or services. It is can also be temporary project teams.",
  },
  {
    id: "csc311_m2l3_027",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "A ______ organizational structure is centered on work teams or groups of various sizes, which can be temporary.",
    options: ["Hierarchical", "Virtual", "Team", "Multidimensional"],
    correctAnswer: 2,
    explanation:
      "Team organizational structure is a structure centered on work teams or groups, various sizes and temporary or various sizes.",
  },
  {
    id: "csc311_m2l3_028",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "A ______ organizational structure employs individuals, groups, or complete business units in geographically dispersed areas.",
    options: ["Virtual", "Traditional", "Flat", "Project"],
    correctAnswer: 0,
    explanation:
      "A virtual organizational structure employs individuals, groups, or complete business units in geographically dispersed areas.",
  },
  {
    id: "csc311_m2l3_029",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Virtual organizational structures can involve people in different countries operating in different ______ and cultures.",
    options: [
      "authority levels",
      "corporate areas",
      "hierarchical levels",
      "time zones",
    ],
    correctAnswer: 3,
    explanation:
      "These can involve people in different countries operating in different time zones and different cultures.",
  },
  {
    id: "csc311_m2l3_030",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Multidimensional structures simultaneously stress traditional corporate areas and important ______.",
    options: [
      "time zones",
      "product lines",
      "unfreezing techniques",
      "data models",
    ],
    correctAnswer: 1,
    explanation:
      "It’s advantage is the ability to simultaneously stress both traditional corporate areas and important product lines.",
  },
  {
    id: "csc311_m2l3_031",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "A flat organizational structure contains an increased and highly complex number of management layers.",
    options: ["Maybe", "False", "True", "I don't know"],
    correctAnswer: 1,
    explanation:
      "False. Flat organizational structure: An organizational structure with a reduced number of layers of management.",
  },
  {
    id: "csc311_m2l3_032",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "______ is defined as a set of major understandings and assumptions shared by a group.",
    options: ["Culture", "Politics", "Structure", "Technology"],
    correctAnswer: 0,
    explanation:
      "Culture: A set of major understandings and assumptions shared by a group.",
  },
  {
    id: "csc311_m2l3_033",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Organizational ______ deals with how for-profit and non-profit organizations plan for, implement, and handle change.",
    options: ["culture", "change", "learning", "modeling"],
    correctAnswer: 1,
    explanation:
      "Organizational change: Deals with how for-profit and non-profit organizations plan for, implement, and handle change.",
  },
  {
    id: "csc311_m2l3_034",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Organizational ______ is the way organizations adapt to new conditions or alter their practices over time.",
    options: ["learning", "unfreezing", "refreezing", "redesign"],
    correctAnswer: 0,
    explanation:
      "Organizational learning: The way organizations adapt to new conditions or alter their practices over time.",
  },
  {
    id: "csc311_m2l3_035",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "A change model represents change theories by identifying the ______ of change and the best way to implement them.",
    options: ["roots", "costs", "phases", "outcomes"],
    correctAnswer: 2,
    explanation:
      "A change model represents change theories by identifying the phases of change and the best way to implement them.",
  },
  {
    id: "csc311_m2l3_036",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The three-stage approach for a change model consists of unfreezing, moving, and refreezing.",
    options: ["True", "I don't know", "False", "Maybe"],
    correctAnswer: 0,
    explanation:
      "True. A three-stage approach for change are unfreezing, moving and refreezing.",
  },
  {
    id: "csc311_m2l3_037",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "______ is the stage of ceasing old habits and creating a climate that is receptive to change.",
    options: ["Moving", "Refreezing", "Unfreezing", "Reengineering"],
    correctAnswer: 2,
    explanation:
      "Unfreezing is ceasing old habits and creating a climate that is receptive to change.",
  },
  {
    id: "csc311_m2l3_038",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "______ is the stage of learning new work methods, behaviors, and systems.",
    options: ["Unfreezing", "Moving", "Refreezing", "Outsourcing"],
    correctAnswer: 1,
    explanation: "Moving is learning new work methods, behaviors, and systems.",
  },
  {
    id: "csc311_m2l3_039",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "______ involves reinforcing changes to make the new process second nature, accepted, and part of the job.",
    options: ["Unfreezing", "Moving", "Diffusing", "Refreezing"],
    correctAnswer: 3,
    explanation:
      "Refreezing involves reinforcing changes to make the new process second nature, accepted, and part of the job.",
  },
  {
    id: "csc311_m2l3_040",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Reengineering is also referred to as Process ______.",
    options: ["resolution", "redesign", "acceptance", "optimization"],
    correctAnswer: 1,
    explanation: "Reengineering: Also called ‘Process redesign’.",
  },
  {
    id: "csc311_m2l3_041",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Reengineering is the ______ redesign of business processes, organizational structures, information systems, and values.",
    options: ["continuous", "gradual", "routine", "radical"],
    correctAnswer: 3,
    explanation:
      "Reengineering: The radical redesign of business processes, organizational structures, information systems, and values...",
  },
  {
    id: "csc311_m2l3_042",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "A major goal of reengineering is to achieve a ______ in business results.",
    options: [
      "breakthrough",
      "continuous flow",
      "minor improvement",
      "minor cost-cut",
    ],
    correctAnswer: 0,
    explanation: "...to achieve a breakthrough in business results.",
  },
  {
    id: "csc311_m2l3_043",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Reengineering requires finding and vigorously challenging old rules.",
    options: ["False", "I don't know", "True", "Maybe"],
    correctAnswer: 2,
    explanation:
      "True. Rules: Reengineering requires finding and vigorously challenging old rules.",
  },
  {
    id: "csc311_m2l3_044",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "______ is constantly seeking ways to improve business processes to add value to products and services.",
    options: [
      "Reengineering",
      "Unfreezing",
      "Continuous Improvement",
      "Downsizing",
    ],
    correctAnswer: 2,
    explanation:
      "Continuous Improvement: Constantly seeking ways to improve business processes to add value to products and services.",
  },
  {
    id: "csc311_m2l3_045",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Business Process Reengineering involves top-down change driven by senior executives, while Continuous Improvement is bottom-up change driven by ______.",
    options: ["workers", "outsiders", "managers", "the environment"],
    correctAnswer: 0,
    explanation:
      "BPR: Top-down change driven by senior executives. Continuous Improvement: Bottom-up change driven by workers.",
  },
  {
    id: "csc311_m2l3_046",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Business Process Reengineering is ______ in scope, cutting across multiple departments.",
    options: ["narrow", "broad", "continuous", "routine"],
    correctAnswer: 1,
    explanation: "BPR: Broad in scope; cuts across departments.",
  },
  {
    id: "csc311_m2l3_047",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Continuous Improvement is ______ in scope, focusing on tasks in a given area.",
    options: ["broad", "radical", "narrow", "top-down"],
    correctAnswer: 2,
    explanation:
      "Continuous Improvement: Narrow in scope; focus is on tasks in a given area.",
  },
  {
    id: "csc311_m2l3_048",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "User ______ refers to the degree to which users feel that a system meets their expectations, needs, and preferences.",
    options: ["acceptance", "infusion", "satisfaction", "diffusion"],
    correctAnswer: 2,
    explanation:
      "User satisfaction refers to the degree to which users feels that a system, product or service meers their expectations, needs and preferences.",
  },
  {
    id: "csc311_m2l3_049",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Technology ______ is the willingness of users to adopt and use a new technology or system.",
    options: ["satisfaction", "unfreezing", "refreezing", "acceptance"],
    correctAnswer: 3,
    explanation:
      "Technology acceptance is the willingness of users to adopt and use a new technology or system.",
  },
  {
    id: "csc311_m2l3_050",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Technology acceptance focuses on whether users find the technology valuable and easy enough to integrate into their ______ activities.",
    options: ["daily", "occasional", "executive", "complex"],
    correctAnswer: 0,
    explanation:
      "It focuses on whether users find the technology valuable and easy enough to integerate into their tasks or daily activities.",
  },
  {
    id: "csc311_m2l3_051",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "User satisfaction comes first, while technology acceptance comes after actual use.",
    options: ["Maybe", "False", "I don't know", "True"],
    correctAnswer: 1,
    explanation:
      "False. Technology acceptance comes first while user satisfaction comes after actual use.",
  },
  {
    id: "csc311_m2l3_052",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The Technology Acceptance Model (TAM) describes factors leading to higher levels of ______ and usage of technology.",
    options: ["diffusion", "acceptance", "satisfaction", "reengineering"],
    correctAnswer: 1,
    explanation:
      "Technology acceptance model (TAM): A model that describes the factors leading to higher levels of acceptance and usage of technology.",
  },
  {
    id: "csc311_m2l3_053",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "TAM specifies factors that lead to higher acceptance, such as perceived usefulness and perceived ______.",
    options: [
      "cost to build",
      "hardware requirements",
      "ease of use",
      "physical size",
    ],
    correctAnswer: 2,
    explanation:
      "Specifies factors that can lead to higher acceptance and usage of technology (perceived usefulness and perceived ease of use).",
  },
  {
    id: "csc311_m2l3_054",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Technology ______ is a measure of the widespread use of technology.",
    options: ["infusion", "acceptance", "resolution", "diffusion"],
    correctAnswer: 3,
    explanation:
      "Technology diffusion: Measure of widespread use of technology.",
  },
  {
    id: "csc311_m2l3_055",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Technology ______ is the extent to which technology permeates a department.",
    options: ["infusion", "diffusion", "unfreezing", "refreezing"],
    correctAnswer: 0,
    explanation:
      "Technology infusion: Extent to which technology permeates a department.",
  },
  {
    id: "csc311_m2l3_056",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Quality is the ability of a product or service to meet or exceed customer ______.",
    options: ["specifications", "costs", "inputs", "expectations"],
    correctAnswer: 3,
    explanation:
      "Quality: The ability of a product (including services) to meet or exceed customer expectations.",
  },
  {
    id: "csc311_m2l3_057",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "______ is a collection of approaches, tools, and techniques that offers a commitment to quality throughout the organization.",
    options: [
      "Total Quality Management",
      "Six Sigma",
      "Technology Diffusion",
      "Process Reengineering",
    ],
    correctAnswer: 0,
    explanation:
      "Total Quality Management: A collection of approaches, tools, and techniques, that offers a commitment to quality throughout the organization.",
  },
  {
    id: "csc311_m2l3_058",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "______ is a statistical term that means products and services will meet quality standards 99.9997% of the time.",
    options: [
      "Total Quality Management",
      "Unfreezing",
      "Continuous Improvement",
      "Six Sigma",
    ],
    correctAnswer: 3,
    explanation:
      "Six Sigma: A statistical term that means products and services will meet quality standards 99.9997% of the time.",
  },
  {
    id: "csc311_m2l3_059",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "In a normal distribution curve, six standard deviations (Six Sigma) is ______% of the area under the curve.",
    options: ["95.0", "99.0", "99.9997", "100.0"],
    correctAnswer: 2,
    explanation:
      "In a normal distribution curve used in statistics, six standard deviations (Six Sigma) is 99.9997% of the area under the curve.",
  },
  {
    id: "csc311_m2l3_060",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Six Sigma was originally developed at Motorola, Inc. in the mid 1980s.",
    options: ["Maybe", "True", "False", "I don't know"],
    correctAnswer: 1,
    explanation:
      "True. Six Sigma was developed at Motorola, Inc. in the mid 1980s.",
  },
  {
    id: "csc311_m2l3_061",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "______ involves contracting with outside professional services to meet specific business needs.",
    options: ["Downsizing", "Outsourcing", "Reengineering", "Refreezing"],
    correctAnswer: 1,
    explanation:
      "Outsourcing involves contracting with outside professional services to meet specific business needs.",
  },
  {
    id: "csc311_m2l3_062",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Outsourcing allows the company to focus more closely on its ______ business.",
    options: ["secondary", "external", "temporary", "core"],
    correctAnswer: 3,
    explanation:
      "This approach allows the company to focus more closely on its core business and to target its limited resources to meet strategic goals.",
  },
  {
    id: "csc311_m2l3_063",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "______ involves reducing the number of employees to reduce payroll costs.",
    options: ["Outsourcing", "Infusion", "Diffusion", "Downsizing"],
    correctAnswer: 3,
    explanation:
      "Downsizing involves reducing the number of employees to reduce payroll costs.",
  },
  {
    id: "csc311_m2l3_064",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Contracting for computer resources to rapidly respond to an organization's varying workflow is known as ______ computing.",
    options: ["hierarchical", "continuous", "spatial", "on-demand"],
    correctAnswer: 3,
    explanation:
      "on-demand computing: Contracting for computer resources to rapidly respond to an organization’s varying workflow.",
  },
  {
    id: "csc311_m2l3_065",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "On-demand computing is also sometimes called utility computing.",
    options: ["I don't know", "True", "Maybe", "False"],
    correctAnswer: 1,
    explanation: "True. Also called on-demand business and utility computing.",
  },
  {
    id: "csc311_m2l3_066",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "To deliver genuine benefits, information systems must be built with a clear understanding of the ______ in which they will be used.",
    options: ["vendor", "organization", "hardware", "subschema"],
    correctAnswer: 1,
    explanation:
      "To deliver genuine benefits, information systems must be built with a clear understanding of the organization in which they will be used.",
  },
  {
    id: "csc311_m2l3_067",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "When planning a new system, you should consider the principal ______ groups affected by the system and the attitudes of workers.",
    options: ["hierarchical", "external", "executive", "interest"],
    correctAnswer: 3,
    explanation:
      "The principal interest groups affected by the system and the attitudes of workers who will be using the system.",
  },
  {
    id: "csc311_m2l3_068",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "______ are designed to support organizational decision making through 'What-if' analysis.",
    options: [
      "Decision Support Systems (DSS)",
      "Office Automation Systems",
      "Expert Systems",
      "Collaboration Technologies",
    ],
    correctAnswer: 0,
    explanation:
      "Decision Support Systems (DSSs): Designed to support organizational decision making. “What-if” analysis.",
  },
  {
    id: "csc311_m2l3_069",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Microsoft Excel is given as an example of a ______ tool.",
    options: [
      "Functional Area IS",
      "Expert System",
      "Groupware",
      "Decision Support System (DSS)",
    ],
    correctAnswer: 3,
    explanation: "Example of a DSS tool: Microsoft Excel.",
  },
  {
    id: "csc311_m2l3_070",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Office Automation Systems (OASs) include activities such as communicating and ______, and document preparation.",
    options: [
      "rule-making",
      "top-down redesign",
      "six sigma compliance",
      "scheduling",
    ],
    correctAnswer: 3,
    explanation:
      "Office Automation Systems (OASs) Examples: Communicating and scheduling, Document preparation, Analyzing data, Consolidating information.",
  },
  {
    id: "csc311_m2l3_071",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "______ mimic human expertise by manipulating knowledge through Rules (If-then) and Inference.",
    options: [
      "Decision Support Systems",
      "Virtual teams",
      "Expert Systems",
      "Office Automation Systems",
    ],
    correctAnswer: 2,
    explanation:
      "Expert Systems (ESs): Mimics human expertise by manipulating knowledge, Rules (If-then), Inference.",
  },
  {
    id: "csc311_m2l3_072",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Expert Systems manipulate knowledge primarily using graphical models and structured reports.",
    options: ["Maybe", "True", "I don't know", "False"],
    correctAnswer: 3,
    explanation:
      "False. Expert Systems mimic human expertise by manipulating knowledge via Rules (If-then) and Inference.",
  },
  {
    id: "csc311_m2l3_073",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Videoconferencing, Groupware, and Electronic Meeting Systems (EMSs) are examples of ______.",
    options: [
      "Expert Systems",
      "Decision Support Systems",
      "Collaboration Technologies",
      "On-demand computing",
    ],
    correctAnswer: 2,
    explanation:
      "Collaboration Technologies: Virtual teams, Videoconferencing, Groupware, Electronic Meeting Systems (EMSs).",
  },
  {
    id: "csc311_m2l3_074",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "Functional Area Information Systems are geared toward specific areas in the company, such as ______.",
    options: [
      "Executive planning",
      "What-if analysis",
      "External environment",
      "Human Resources",
    ],
    correctAnswer: 3,
    explanation:
      "Functional Area Information Systems: Geared toward specific areas in the company: Human Resources, Benefits, Marketing.",
  },
  {
    id: "csc311_m2l3_075",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The Decision-Making Levels of an organization consist of the Executive level, the Managerial level, and the ______ level.",
    options: ["Tactical", "Strategic", "Technical", "Operational"],
    correctAnswer: 3,
    explanation:
      "Decision-Making Levels of an Organization: Executive level (top), Managerial level (middle), Operational level (bottom).",
  },
  {
    id: "csc311_m2l3_076",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The Executive level (top) handles long-term, ______ decisions.",
    options: ["structured", "semistructured", "routine", "unstructured"],
    correctAnswer: 3,
    explanation:
      "Executive level (top): Long-term decisions, Unstructured decisions.",
  },
  {
    id: "csc311_m2l3_077",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The Managerial level (middle) handles decisions covering weeks and months, which are ______ decisions.",
    options: [
      "unstructured",
      "semistructured",
      "permanent",
      "fully structured",
    ],
    correctAnswer: 1,
    explanation:
      "Managerial level (middle): Decisions covering weeks and months, Semistructured decisions.",
  },
  {
    id: "csc311_m2l3_078",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The Operational level (bottom) handles day-to-day, ______ decisions.",
    options: ["unstructured", "semistructured", "strategic", "structured"],
    correctAnswer: 3,
    explanation:
      "Operational level (bottom): Day-to-day decisions, Structured decisions.",
  },
  {
    id: "csc311_m2l3_079",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The managerial level primarily focuses on day-to-day, structured decisions.",
    options: ["True", "I don't know", "False", "Maybe"],
    correctAnswer: 2,
    explanation:
      "False. The Operational level handles day-to-day, structured decisions. The Managerial level handles semistructured decisions covering weeks and months.",
  },
  {
    id: "csc311_m2l3_080",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "According to the change model, ceasing old habits and creating a climate receptive to change is part of the ______ stage.",
    options: ["Moving", "Refreezing", "Infusion", "Unfreezing"],
    correctAnswer: 3,
    explanation:
      "Unfreezing is ceasing old habits and creating a climate that is receptive to change.",
  },
  {
    id: "csc311_m2l3_081",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "According to the change model, reinforcing changes to make the new process second nature is the ______ stage.",
    options: ["Refreezing", "Moving", "Unfreezing", "Outsourcing"],
    correctAnswer: 0,
    explanation:
      "Refreezing involves reinforcing changes to make the new process second nature, accepted, and part of the job.",
  },
  {
    id: "csc311_m2l3_082",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "In the context of business process redesign, the goal of reengineering is often to achieve a ______ in business results.",
    options: [
      "breakthrough",
      "minor reduction",
      "subtle shift",
      "standard deviation",
    ],
    correctAnswer: 0,
    explanation:
      "Reengineering... to achieve a breakthrough in business results.",
  },
  {
    id: "csc311_m2l3_083",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "The two-way relationship between organizations and information technology is mediated by factors such as culture, structure, politics, and ______.",
    options: [
      "physical hardware",
      "memory sizes",
      "management decisions",
      "CPU speeds",
    ],
    correctAnswer: 2,
    explanation:
      "Other factors mediating the relationship include the organizational culture, structure, politics, business processes, and environment... decisions made—or not made—by managers.",
  },
  {
    id: "csc311_m2l3_084",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "An organization’s structure depends on its goals and approach to management, but it has no impact on how it uses information systems.",
    options: ["False", "Maybe", "I don't know", "True"],
    correctAnswer: 0,
    explanation:
      "False. An organization’s structure depends on its goals and approach to management, and can affect how it views and uses information systems.",
  },
  {
    id: "csc311_m2l3_085",
    course: "CSC 311",
    chapter: "Chapter 3",
    text: "MAA Bozell, a communications company in India, used ______ to improve the quality for all of its business processes.",
    options: [
      "Six Sigma",
      "Total Quality Management (TQM)",
      "Expert Systems",
      "Groupware",
    ],
    correctAnswer: 1,
    explanation:
      "Examples: MAA Bozell, a communications company in India, used TQM to improve the quality for all of its business processes.",
  },
];

export default csc311Chapter3;
