import { QuestionV2 } from "@/lib/quiz-types";

const csc311Chapter5: QuestionV2[] = [
  {
    id: "csc311_ch5_001",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "A Strategic Information System (SIS) is a system that helps companies change or otherwise alter their business strategy and/or ______.",
    options: [
      "human resources",
      "structure",
      "financial audits",
      "customer feedback",
    ],
    correctAnswer: 1,
    explanation:
      "A Strategic Information System (SIS) is a system that helps companies change or otherwise alter their business strategy and/or structure.",
  },
  {
    id: "csc311_ch5_002",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "SIS is typically utilized to streamline and quicken the reaction time to ______ changes and aid it in achieving a competitive advantage.",
    options: ["environmental", "procedural", "hardware", "employee"],
    correctAnswer: 0,
    explanation:
      "It is typically utilized to streamline and quicken the reaction time to environmental changes and aid it in achieving a competitive advantage.",
  },
  {
    id: "csc311_ch5_003",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "A strategic system alters the way an organization does business, the way it competes, or the way it deals with its customers or ______.",
    options: ["investors", "suppliers", "managers", "regulators"],
    correctAnswer: 1,
    explanation:
      "A strategic system alters the way an organization does business or the way it competes or the way it deals with its customers or suppliers.",
  },
  {
    id: "csc311_ch5_004",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Most strategic systems guarantee a company higher profits rather than simply enabling it to be an effective competitor.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 1,
    explanation:
      "False. Some systems offer a clear competitive advantage (higher profits/market share), but 'most strategic systems - enable a company to be an effective competitor'.",
  },
  {
    id: "csc311_ch5_005",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "A strategic system supports or shapes a business unit's ______ strategy.",
    options: ["competitive", "budgetary", "training", "procurement"],
    correctAnswer: 0,
    explanation:
      "What are Strategic Systems? A strategic system supports or shapes a business unit's competitive strategy.",
  },
  {
    id: "csc311_ch5_006",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "An outward looking strategic system focuses on customers, competitors, and ______.",
    options: ["systems", "procedures", "environments", "employees"],
    correctAnswer: 2,
    explanation: "outward looking: customers, competitors, environments.",
  },
  {
    id: "csc311_ch5_007",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "An inward looking strategic system focuses on employees, systems, and ______.",
    options: ["customers", "competitors", "environments", "procedures"],
    correctAnswer: 3,
    explanation: "inward looking: employees, systems, procedures.",
  },
  {
    id: "csc311_ch5_008",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "SIS utilizes ______ systems to enable a strategic approach to align IS or IT with an organization's business strategies.",
    options: [
      "Legacy archive",
      "Decision support",
      "Redundant backup",
      "Manual filing",
    ],
    correctAnswer: 1,
    explanation:
      "Key features: Decision support systems that enable to develop a strategic approach to align Information Systems (IS) or Information Technologies (IT) with an organization's business strategies.",
  },
  {
    id: "csc311_ch5_009",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "SIS primarily utilizes ______ solutions to integrate and link business processes to meet enterprise objectives.",
    options: [
      "Enterprise resource planning",
      "Local area network",
      "Cost accounting",
      "Virtual reality",
    ],
    correctAnswer: 0,
    explanation:
      "Key features: Primarily Enterprise resource planning solutions that integrate/link the business processes to meet the enterprise objectives for the optimization of the enterprise resources.",
  },
  {
    id: "csc311_ch5_010",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Database systems in SIS use ______ capabilities to make the best use of available corporate information for marketing, production, and innovation.",
    options: [
      "hardware clustering",
      "data mining",
      "cloud offloading",
      "manual querying",
    ],
    correctAnswer: 1,
    explanation:
      "Database systems with the 'data mining' capabilities to make the best use of available corporate information for marketing, production, promotion and innovation.",
  },
  {
    id: "csc311_ch5_011",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The three general types of information systems that are developed and in general use are financial systems, operational systems, and ______ systems.",
    options: ["administrative", "strategic", "networking", "hardware"],
    correctAnswer: 1,
    explanation:
      "The three general types of information systems that are developed and in general use are financial systems, operational systems, and strategic systems.",
  },
  {
    id: "csc311_ch5_012",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Financial, operational, and strategic systems are mutually exclusive categories that never overlap.",
    options: ["Maybe", "I don't know", "True", "False"],
    correctAnswer: 3,
    explanation:
      "False. 'These categories are not mutually exclusive and, in fact, they always overlap to some [degree].'",
  },
  {
    id: "csc311_ch5_013",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Well-directed financial systems and operational systems may well become ______ systems for a particular organization.",
    options: ["obsolete", "outsourced", "strategic", "redundant"],
    correctAnswer: 2,
    explanation:
      "Well-directed financial systems and operational systems may well become the strategic systems for a particular organization.",
  },
  {
    id: "csc311_ch5_014",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Strategic systems generally focus on external factors and involve a ______ degree of project risk.",
    options: ["low", "moderate", "high", "zero"],
    correctAnswer: 2,
    explanation:
      "Strategic systems: External focus... high degree of project risk.",
  },
  {
    id: "csc311_ch5_015",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Elements of Strategic Management include Innovation, Role of IT, Competitive intelligence, the Internet, and ______ advantage.",
    options: ["sustainable", "temporary", "accidental", "unpredictable"],
    correctAnswer: 0,
    explanation:
      "Elements of Strategic Management: Innovation, Role of IT, Competitive intelligence, Internet, Competitive strategy and sustainable advantage.",
  },
  {
    id: "csc311_ch5_016",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The Competitive Forces model is used to describe the interaction of external influences, specifically ______ and opportunities.",
    options: ["liabilities", "threats", "budgets", "infrastructures"],
    correctAnswer: 1,
    explanation:
      "Competitive Forces model: used to describe the interaction of external influences -- threats and opportunities -- that affect an organization’s strategy...",
  },
  {
    id: "csc311_ch5_017",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Competitive advantage is a significant, ______ benefit to a company over its competition.",
    options: ["short-term", "long-term", "accidental", "marginal"],
    correctAnswer: 1,
    explanation:
      "Competitive Advantage: Significant, long-term benefit to a company over its competition...",
  },
  {
    id: "csc311_ch5_018",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Which of the following is NOT one of the four basic competitive strategies businesses use to deal with competitive forces?",
    options: [
      "Product Differentiation",
      "Cost leadership",
      "Supplier monopolization",
      "Focused differentiation",
    ],
    correctAnswer: 2,
    explanation:
      "The four strategies are: Product Differentiation, Cost leadership, Focused differentiation, and Cost Focus.",
  },
  {
    id: "csc311_ch5_019",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "______ is a competitive strategy for creating brand loyalty by developing products and services different from what the competition offers.",
    options: [
      "Cost leadership",
      "Differentiation",
      "Cost Focus",
      "Strategic alliance",
    ],
    correctAnswer: 1,
    explanation:
      "1. Differentiation: competitive strategy for creating brand loyalty. Develop products & services which are different from what the competition offers.",
  },
  {
    id: "csc311_ch5_020",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "______ aims to prevent new competitors from entering markets by producing goods/services at a lower price based on efficient operations.",
    options: [
      "Cost leadership",
      "Focused differentiation",
      "Strategic innovation",
      "Mergers & acquisitions",
    ],
    correctAnswer: 0,
    explanation:
      "2. Cost leadership: to prevent new competitors from entering their markets, businesses produce goods/services at lower price than competition.",
  },
  {
    id: "csc311_ch5_021",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Focused differentiation involves developing a new market niche for ______ products or services.",
    options: ["generic", "specialized", "outdated", "bulk"],
    correctAnswer: 1,
    explanation:
      "3. Focused differentiation: develop new market niche for specialized products or services.",
  },
  {
    id: "csc311_ch5_022",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Cost Focus is a strategy where a company serves a broad target market with products at a significantly higher cost.",
    options: ["I don't know", "Maybe", "True", "False"],
    correctAnswer: 3,
    explanation:
      "False. Cost Focus: Company serves narrow market segment with product/service which it offers at a significantly lower cost than competitors.",
  },
  {
    id: "csc311_ch5_023",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Porter’s Five-force model identifies the threat of new competitors, bargaining power of suppliers/customers, substitute products, and ______.",
    options: [
      "taxation policies",
      "internal audits",
      "rivalry within the industry",
      "technological decay",
    ],
    correctAnswer: 2,
    explanation:
      "Five-forces model identifies key factors: threat of new competitors, bargaining power of suppliers, bargaining power of customers, substitute products, rivalry within the industry.",
  },
  {
    id: "csc311_ch5_024",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The threat of new competitors can be addressed by using IT to erect barriers to entry.",
    options: ["Maybe", "I don't know", "False", "True"],
    correctAnswer: 3,
    explanation:
      "True. Threat of new competitors: Erect barriers to entry: use IT to slow down new firms entering market.",
  },
  {
    id: "csc311_ch5_025",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "A firm can intensify rivalry among competitors by changing the basis of competition, so they no longer compete just on a ______ basis.",
    options: ["price", "quality", "location", "speed"],
    correctAnswer: 0,
    explanation:
      "Intensify rivalry among competitors... you are now differentiated from competition, no longer compete just on price basis.",
  },
  {
    id: "csc311_ch5_026",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "To address pressures from potential substitute products, a firm should try to deliver products with better ______.",
    options: ["packaging", "value", "marketing", "color schemes"],
    correctAnswer: 1,
    explanation:
      "Pressures from potential substitute products: Deliver products with better value.",
  },
  {
    id: "csc311_ch5_027",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "To deter customers from switching to a competitor, an organization can introduce ______ costs.",
    options: ["manufacturing", "switching", "overhead", "variable"],
    correctAnswer: 1,
    explanation:
      "Bargaining power of customers: Introduce switching costs... deters customers from switching.",
  },
  {
    id: "csc311_ch5_028",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "To counteract the bargaining power of suppliers, a firm can use IS to maintain information on ______ sources of supply.",
    options: ["obsolete", "expensive", "alternative", "internal"],
    correctAnswer: 2,
    explanation:
      "Bargaining power of suppliers: Develop Alternatives: use IS to maintain information on available alternative sources of supply.",
  },
  {
    id: "csc311_ch5_029",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Internal innovation, internal growth, mergers & acquisitions, and ______ are tactical moves in pursuing a strategy.",
    options: [
      "tax evasion",
      "strategic alliances",
      "outsourcing all staff",
      "liquidating assets",
    ],
    correctAnswer: 1,
    explanation:
      "Tactical Moves in Pursuing a Strategy: Internal innovation... internal growth... Mergers & acquisitions... Strategic alliances.",
  },
  {
    id: "csc311_ch5_030",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "An agreement between two or more companies that involves the joint production and distribution of goods and services is called a ______.",
    options: ["hostile takeover", "merger", "strategic alliance", "tax haven"],
    correctAnswer: 2,
    explanation:
      "Strategic alliance: An agreement between two or more companies that involves the joint production and distribution of goods and services.",
  },
  {
    id: "csc311_ch5_031",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "A company may become ______ without the introduction of new goods and/or services.",
    options: ["monopolistic", "stagnant", "globalized", "hyperactive"],
    correctAnswer: 1,
    explanation:
      "Creating new goods or services: A company may become stagnant without the introduction of new goods and/or services.",
  },
  {
    id: "csc311_ch5_032",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "SABRE, an airline reservation system, is given as an example of ______.",
    options: [
      "a failed IT project",
      "creating light foods",
      "using information systems for strategic purposes",
      "a merger & acquisition",
    ],
    correctAnswer: 2,
    explanation:
      "Using information systems for strategic purposes: IS for improving organizational effectiveness. E.g., SABRE (airline reservation system).",
  },
  {
    id: "csc311_ch5_033",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Primary Value Chain Activities include Inbound Logistics, Operations, Outbound Logistics, Marketing & Sales, and ______.",
    options: [
      "Research & Development",
      "Human Resources",
      "Service",
      "Procurement",
    ],
    correctAnswer: 2,
    explanation:
      "Primary Value Chain Activities: Inbound Logistics > Operations > Outbound Logistics > Marketing & Sales > Service.",
  },
  {
    id: "csc311_ch5_034",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The value system only includes the firm-specific value chain and ignores the upstream suppliers and downstream buyers.",
    options: ["Maybe", "False", "True", "I don't know"],
    correctAnswer: 1,
    explanation:
      "False. The firm's value chain links to the value chains of upstream suppliers and downstream buyers. The result is a larger stream of activities known as the value system.",
  },
  {
    id: "csc311_ch5_035",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "In the Value Chain, Upstream Chains relate to ______.",
    options: ["Customers", "Suppliers", "Competitors", "Employees"],
    correctAnswer: 1,
    explanation:
      "Based on the Value Chain diagram: Upstream Chains of Suppliers.",
  },
  {
    id: "csc311_ch5_036",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "In the Value Chain, Downstream Chains relate to ______.",
    options: ["Suppliers", "Investors", "Customers", "Regulators"],
    correctAnswer: 2,
    explanation:
      "Based on the Value Chain diagram: Downstream Chains of Customers.",
  },
  {
    id: "csc311_ch5_037",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "An EDI-Based Purchasing System is an example of a strategic IS mapped onto the ______ activity of the value chain.",
    options: [
      "Operations",
      "Outbound Logistics",
      "Inbound Logistics",
      "Service",
    ],
    correctAnswer: 2,
    explanation:
      "Value Chain diagram maps 'EDI-Based Purchasing System' to 'Inbound Logistics'.",
  },
  {
    id: "csc311_ch5_038",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Telemaintenance Expert Systems are mapped onto the ______ activity of the value chain.",
    options: [
      "Operations",
      "Marketing and Sales",
      "Inbound Logistics",
      "Service",
    ],
    correctAnswer: 3,
    explanation:
      "Value Chain diagram maps 'Telemaintenance Expert Systems' to 'Service'.",
  },
  {
    id: "csc311_ch5_039",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The value chain model highlights primary or support activities that add a margin of ______ to a firm’s products or services.",
    options: ["error", "time", "value", "cost"],
    correctAnswer: 2,
    explanation:
      "value chain model: highlights the primary or support activities that add a margin of value to a firm’s products or services.",
  },
  {
    id: "csc311_ch5_040",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Operations activities in the value chain involve storing products and delivering them.",
    options: ["Maybe", "True", "I don't know", "False"],
    correctAnswer: 3,
    explanation:
      "False. Operations - transformation of inputs to finished goods. Outbound logistics involves storing products and delivering them.",
  },
  {
    id: "csc311_ch5_041",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "In the value chain, Operations involves the ______.",
    options: [
      "storing of products",
      "establishing a customer need",
      "transformation of inputs to finished goods",
      "after-sale service",
    ],
    correctAnswer: 2,
    explanation: "Operations - transformation of inputs to finished goods.",
  },
  {
    id: "csc311_ch5_042",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "A physical value chain can be mirrored with information to produce a ______ value chain.",
    options: ["redundant", "virtual", "stagnant", "diminished"],
    correctAnswer: 1,
    explanation:
      "Virtual Value Chain: Mirrors with information the physical value chain... produce the virtual V.C.",
  },
  {
    id: "csc311_ch5_043",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Successful use of Strategic Information Systems requires the active support of ______ management, not just MIS management.",
    options: ["Senior", "Local branch", "Supplier", "Temporary"],
    correctAnswer: 0,
    explanation:
      "Organizational Requirements for Successful SIS: Active support of Senior management - not just MIS management.",
  },
  {
    id: "csc311_ch5_044",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The sustainability of a competitive advantage depends on the ______ time that will allow the achievement of that advantage.",
    options: ["lag", "lead", "processing", "downtime"],
    correctAnswer: 1,
    explanation:
      "Sustainability of a competitive advantage depends on: lead time will allow the achievement of competitive advantage.",
  },
  {
    id: "csc311_ch5_045",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "If a strategic system is copied by competitors, your organization will still have ______ the marketplace.",
    options: ["lost", "bankrupted", "preempted", "alienated"],
    correctAnswer: 2,
    explanation:
      "If copied: Your organization will still have preempted the marketplace.",
  },
  {
    id: "csc311_ch5_046",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "In the first stage of IS use, organizations primarily focused on using information systems to reduce costs and improve ______.",
    options: [
      "brand loyalty",
      "productivity",
      "market share",
      "revenue potential",
    ],
    correctAnswer: 1,
    explanation:
      "In the first stage, organizations focused on using information systems to reduce costs and improve productivity.",
  },
  {
    id: "csc311_ch5_047",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "In the first stage of IS use, companies generally ignored the ______ potential and did not look for opportunities to increase sales.",
    options: ["revenue", "cost-saving", "productivity", "hardware"],
    correctAnswer: 0,
    explanation:
      "In this stage, companies generally ignored the revenue potential, not looking for opportunities to use information systems to increase sales.",
  },
  {
    id: "csc311_ch5_048",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The second stage of IS use was defined by Porter and was oriented toward gaining a ______ advantage.",
    options: ["technological", "competitive", "logistical", "bureaucratic"],
    correctAnswer: 1,
    explanation:
      "The second stage was defined by Porter and others. It was oriented toward gaining a competitive advantage.",
  },
  {
    id: "csc311_ch5_049",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "In Performance-based management (the third stage), companies only consider strategic advantage and ignore all costs.",
    options: ["True", "Maybe", "I don't know", "False"],
    correctAnswer: 3,
    explanation:
      "False. In this third stage, companies carefully consider both strategic advantage and costs.",
  },
  {
    id: "csc311_ch5_050",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Productivity is calculated as the Output achieved divided by the ______ required.",
    options: ["Profit", "Time", "Input", "Labor"],
    correctAnswer: 2,
    explanation: "Productivity: Output achieved divided by input required.",
  },
  {
    id: "csc311_ch5_051",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The formula for Productivity is (Output / Input) × 100%.",
    options: ["False", "Maybe", "True", "I don't know"],
    correctAnswer: 2,
    explanation: "True. Productivity = (Output / Input) × 100%.",
  },
  {
    id: "csc311_ch5_052",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "A higher level of output for a given level of input means ______ productivity.",
    options: ["lower", "stagnant", "greater", "negative"],
    correctAnswer: 2,
    explanation:
      "Higher level of output for a given level of input means greater productivity.",
  },
  {
    id: "csc311_ch5_053",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "______ investigates the additional profits or benefits generated as a percentage of the investment in IS technology.",
    options: [
      "Market share",
      "Total cost of ownership",
      "Return on investment (ROI)",
      "System integration",
    ],
    correctAnswer: 2,
    explanation:
      "Return on investment (ROI): One measure of IS value that investigates the additional profits or benefits that are generated as a percentage of the investment in IS technology.",
  },
  {
    id: "csc311_ch5_054",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "As a measure of IS value, Market share is defined as the percentage of sales in relation to the ______ market.",
    options: ["local", "global", "total", "projected"],
    correctAnswer: 2,
    explanation:
      "Market share: Percentage of sales in relation to total market.",
  },
  {
    id: "csc311_ch5_055",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Customer awareness and satisfaction as a measure of IS value is based solely on feedback from external users.",
    options: ["True", "I don't know", "False", "Maybe"],
    correctAnswer: 2,
    explanation:
      "False. Customer awareness and satisfaction: Based on feedback from internal and external users.",
  },
  {
    id: "csc311_ch5_056",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The sum of all costs over the life of the information system is known as the ______.",
    options: [
      "Total cost of ownership",
      "Return on investment",
      "Net present value",
      "Capital expenditure",
    ],
    correctAnswer: 0,
    explanation:
      "Total cost of ownership: Sum of all costs over the life of the information system.",
  },
  {
    id: "csc311_ch5_057",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "One of the risks managers must consider is that the costs of development and implementation can be ______ the returns from the new system.",
    options: ["equal to", "irrelevant to", "less than", "greater than"],
    correctAnswer: 3,
    explanation:
      "Costs of development and implementation can be greater than the returns from the new system.",
  },
  {
    id: "csc311_ch5_058",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "People in the ______ component of an IS department tend to focus more on the efficiency of IS functions rather than their effectiveness.",
    options: ["support", "operations", "systems development", "liaisons"],
    correctAnswer: 1,
    explanation:
      "Operations: People in the operations component... tend to focus more on the efficiency of IS functions rather than their effectiveness.",
  },
  {
    id: "csc311_ch5_059",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The ______ component of a typical IS department focuses on specific development projects and ongoing maintenance and review.",
    options: ["operations", "support", "liaisons", "systems development"],
    correctAnswer: 3,
    explanation:
      "Systems development: systems development component of a typical IS department focuses on specific development projects and ongoing maintenance and review.",
  },
  {
    id: "csc311_ch5_060",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The ______ component provides user assistance in hardware and software acquisition and use, data administration, and user training.",
    options: ["support", "operations", "systems development", "liaisons"],
    correctAnswer: 0,
    explanation:
      "Support: The support component of a typical IS department provides user assistance in hardware and software acquisition and use...",
  },
  {
    id: "csc311_ch5_061",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "An information service unit is basically a miniature IS department attached and directly reporting to a ______ area in a large organization.",
    options: ["functional", "external", "competitor", "supplier"],
    correctAnswer: 0,
    explanation:
      "Liaisons (information service units): An information service unit is basically a miniature IS department attached and directly reporting to a functional area in a large organization.",
  },
  {
    id: "csc311_ch5_062",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "An information service unit performs the critical role of liaison between the functional area and IS.",
    options: ["Maybe", "I don't know", "True", "False"],
    correctAnswer: 2,
    explanation:
      "True. Information Service Unit... Performs the critical role of liaison between the functional area and IS.",
  },
  {
    id: "csc311_ch5_063",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The ______ provides users with assistance, training, application development, documentation, equipment selection, and troubleshooting.",
    options: [
      "Database Administrator",
      "Information centre",
      "Webmaster",
      "CIO",
    ],
    correctAnswer: 1,
    explanation:
      "Information centre: Provides users with assistance, training, application development, documentation, equipment selection and setup, standards, technical assistance, and troubleshooting.",
  },
  {
    id: "csc311_ch5_064",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The ______ is a manager at the vice-president level responsible for IS planning, policy, and standards.",
    options: [
      "Chief Information Officer (CIO)",
      "LAN Administrator",
      "Database Administrator",
      "Trainer",
    ],
    correctAnswer: 0,
    explanation:
      "Chief Information Officer (CIO): A manager at the vice-president level responsible for IS planning, policy, and standards.",
  },
  {
    id: "csc311_ch5_065",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The CIO is focused strictly on minimizing departmental payroll rather than supporting corporate goals.",
    options: ["I don't know", "Maybe", "True", "False"],
    correctAnswer: 3,
    explanation: "False. The CIO is 'Focused on supporting corporate goals'.",
  },
  {
    id: "csc311_ch5_066",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Which of the following is an IS role responsible for managing and maintaining the database environment?",
    options: [
      "Webmaster",
      "Database Administrator",
      "LAN Administrator",
      "Trainer",
    ],
    correctAnswer: 1,
    explanation: "Other IS Roles include 'Database Administrator'.",
  },
  {
    id: "csc311_ch5_067",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Strategic alliances are also known as strategic ______.",
    options: ["acquisitions", "partnerships", "fusions", "incorporations"],
    correctAnswer: 1,
    explanation:
      "Four techniques: Strategic alliances (aka strategic partnerships).",
  },
  {
    id: "csc311_ch5_068",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Which automotive partnership is cited as an example of a strategic alliance?",
    options: [
      "Ford + Toyota",
      "Chrysler + Daimler Benz",
      "Honda + Nissan",
      "BMW + Volkswagen",
    ],
    correctAnswer: 1,
    explanation: "Strategic alliance... E.g., Chrysler + Daimler Benz.",
  },
  {
    id: "csc311_ch5_069",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Compaq and Dell are examples given for creating new ______.",
    options: [
      "goods or services",
      "strategic alliances",
      "airline reservation systems",
      "inbound logistics",
    ],
    correctAnswer: 0,
    explanation: "Creating new goods or services... E.g., Compaq, Dell.",
  },
  {
    id: "csc311_ch5_070",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "'Light' foods are given as an example of ______.",
    options: [
      "Creating entirely new product categories",
      "Strategic alliances",
      "Improving existing goods or services",
      "Outbound logistics",
    ],
    correctAnswer: 2,
    explanation:
      "Improving existing goods or services: Small variations to existing goods or services... E.g., “light” foods.",
  },
  {
    id: "csc311_ch5_071",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "The development of a competitive advantage depends not only on the firm-specific value chain, but also on the ______ of which the firm is a part.",
    options: [
      "value system",
      "regulatory framework",
      "merger network",
      "switching cost",
    ],
    correctAnswer: 0,
    explanation:
      "The development of a competitive advantage depends not only on the firm-specific value chain, but also on the value system of which the firm is a part.",
  },
  {
    id: "csc311_ch5_072",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Value chain analysis helps determine where information systems can best be applied to achieve a ______.",
    options: [
      "cost-neutral impact",
      "competitive advantage",
      "tax deduction",
      "merger",
    ],
    correctAnswer: 1,
    explanation:
      "value chain model... highlights the primary or support activities... where information systems can best be applied to achieve a competitive advantage.",
  },
  {
    id: "csc311_ch5_073",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "In the value chain, obtaining raw materials belongs to ______.",
    options: [
      "Outbound logistics",
      "Inbound logistics",
      "Operations",
      "Service activities",
    ],
    correctAnswer: 1,
    explanation: "inbound logistics - obtain raw materials.",
  },
  {
    id: "csc311_ch5_074",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "In the value chain, after-sale service and maintenance belong to ______.",
    options: [
      "Inbound logistics",
      "Marketing/sales",
      "Service activities",
      "Operations",
    ],
    correctAnswer: 2,
    explanation: "Service activities - after-sale service and maintenance.",
  },
  {
    id: "csc311_ch5_075",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "To use IS strategically with the value chain, a firm must identify potentially information-related aspects of each activity and the ______ between them.",
    options: ["linkages", "barriers", "substitutes", "redundancies"],
    correctAnswer: 0,
    explanation:
      "to use IS strategically, must identify potentially info.-related aspects of each activity in value chain and linkages between them.",
  },
  {
    id: "csc311_ch5_076",
    course: "CSC 311",
    chapter: "Chapter 5",
    text: "Strategic Information Systems (SIS) systems facilitate identification of the data collection strategies to help optimize ______ marketing opportunities.",
    options: ["television", "billboard", "database", "door-to-door"],
    correctAnswer: 2,
    explanation:
      "The SIS systems also facilitate identification of the data collection strategies to help optimize database marketing opportunities.",
  },
];

export default csc311Chapter5;
