import { QuestionV2 } from "@/lib/quiz-types";

export const csc311Chapter4_2: QuestionV2[] = [
  {
    id: "csc311_ch42_001",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "What does SDLC stand for in the context of information systems?",
    options: [
      "Software Design and Logical Construction",
      "System Development Life Cycle",
      "Structured Data Logic Control",
      "Software Deployment Logic Cycle",
    ],
    correctAnswer: 1,
    explanation:
      "The SDLC stands for The System Development Life Cycle (SDLC), which is a structured approach to building effective information systems.",
  },
  {
    id: "csc311_ch42_002",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The SDLC is defined as the organized process of designing, developing, and ______ information systems to meet business needs.",
    options: ["implementing", "evaluating", "marketing", "retiring"],
    correctAnswer: 0,
    explanation:
      "The SDLC is 'the organized process of designing, developing, and implementing information systems to meet business needs.'",
  },
  {
    id: "csc311_ch42_003",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "According to the lecture, ad-hoc system development is problematic because it leads to ______.",
    options: [
      "faster deployment times",
      "cost overruns",
      "perfectly aligned user needs",
      "increased system reliability",
    ],
    correctAnswer: 1,
    explanation:
      "The Problem: Ad-hoc system development leads to: Cost overruns, Missed deadlines, Systems that don't meet user needs, Poor quality and reliability.",
  },
  {
    id: "csc311_ch42_004",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Ad-hoc system development typically leads to systems that exceed user expectations.",
    options: ["Maybe", "False", "I don't know", "True"],
    correctAnswer: 1,
    explanation:
      "False. The Problem: Ad-hoc system development leads to... Systems that don't meet user needs.",
  },
  {
    id: "csc311_ch42_005",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The solution to the problems caused by ad-hoc system development is a ______.",
    options: [
      "decentralized management model",
      "disciplined and structured process",
      "rapid unorganized rollout",
      "cloud-based infrastructure",
    ],
    correctAnswer: 1,
    explanation: "The Solution: A disciplined and structured process.",
  },
  {
    id: "csc311_ch42_006",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The SDLC uses a phased approach consisting of ______ core phases.",
    options: ["4", "5", "6", "8"],
    correctAnswer: 2,
    explanation:
      "The 6 Core Phases: Phase 1: Planning, Phase 2: Analysis, Phase 3: Design, Phase 4: Implementation, Phase 5: Testing, Phase 6: Maintenance.",
  },
  {
    id: "csc311_ch42_007",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Phase 1 of the 6 Core Phases of the SDLC is ______.",
    options: ["Analysis", "Design", "Implementation", "Planning"],
    correctAnswer: 3,
    explanation: "Phase 1: Planning.",
  },
  {
    id: "csc311_ch42_008",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Phase 2 of the 6 Core Phases of the SDLC is ______.",
    options: ["Design", "Planning", "Testing", "Analysis"],
    correctAnswer: 3,
    explanation: "Phase 2: Analysis.",
  },
  {
    id: "csc311_ch42_009",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Phase 3 of the 6 Core Phases of the SDLC is ______.",
    options: ["Design", "Implementation", "Analysis", "Maintenance"],
    correctAnswer: 0,
    explanation: "Phase 3: Design.",
  },
  {
    id: "csc311_ch42_010",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Phase 4 of the 6 Core Phases of the SDLC is ______.",
    options: ["Testing", "Design", "Implementation", "Planning"],
    correctAnswer: 2,
    explanation: "Phase 4: Implementation.",
  },
  {
    id: "csc311_ch42_011",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Phase 5 of the 6 Core Phases of the SDLC is ______.",
    options: ["Analysis", "Testing", "Implementation", "Maintenance"],
    correctAnswer: 1,
    explanation: "Phase 5: Testing.",
  },
  {
    id: "csc311_ch42_012",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Phase 6 of the 6 Core Phases of the SDLC is ______.",
    options: ["Maintenance", "Deployment", "Design", "Testing"],
    correctAnswer: 0,
    explanation: "Phase 6: Maintenance.",
  },
  {
    id: "csc311_ch42_013",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The ______ model is a linear, sequential approach where each phase must be fully completed before the next begins.",
    options: ["Iterative", "Agile", "Waterfall", "Spiral"],
    correctAnswer: 2,
    explanation:
      "Waterfall: A linear, sequential approach where each phase must be fully completed before the next begins.",
  },
  {
    id: "csc311_ch42_014",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The ______ model is a cyclic process where the system is built through repeated cycles of refinement, creating progressively more complete versions.",
    options: ["Waterfall", "Iterative", "Linear", "Ad-hoc"],
    correctAnswer: 1,
    explanation:
      "Iterative: A cyclic process where the system is built through repeated cycles of refinement, creating progressively more complete versions.",
  },
  {
    id: "csc311_ch42_015",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The Spiral model is a ______ model that cycles through phases of planning, risk analysis, engineering, and evaluation in iterative loops.",
    options: ["risk-driven", "linear-sequential", "cost-driven", "static"],
    correctAnswer: 0,
    explanation:
      "Spiral: A risk-driven model that cycles through phases of planning, risk analysis, engineering, and evaluation in iterative loops.",
  },
  {
    id: "csc311_ch42_016",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Which SDLC model emphasizes rapid delivery, customer collaboration, and responding to change over strict planning?",
    options: ["Spiral", "Waterfall", "Iterative", "Agile"],
    correctAnswer: 3,
    explanation:
      "Agile: An iterative and incremental approach that emphasizes rapid delivery, customer collaboration, and responding to change over strict planning.",
  },
  {
    id: "csc311_ch42_017",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Identifying and selecting the project is a key activity in the ______ phase.",
    options: ["Analysis", "Design", "Planning", "Implementation"],
    correctAnswer: 2,
    explanation: "Planning Key Activities: Identify and select the project.",
  },
  {
    id: "csc311_ch42_018",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Conducting a Feasibility Study is a key activity that takes place during the ______ phase.",
    options: ["Maintenance", "Planning", "Testing", "Analysis"],
    correctAnswer: 1,
    explanation: "Planning Key Activities: ... Conduct a Feasibility Study.",
  },
  {
    id: "csc311_ch42_019",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "In a Feasibility Study, ______ feasibility answers the question: 'Can we build it?'",
    options: ["Economic", "Schedule", "Technical", "Operational"],
    correctAnswer: 2,
    explanation: "Technical: Can we build it?",
  },
  {
    id: "csc311_ch42_020",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "In a Feasibility Study, ______ feasibility assesses the cost/benefit (ROI).",
    options: ["Operational", "Economic", "Schedule", "Technical"],
    correctAnswer: 1,
    explanation: "Economic: What is the cost/benefit? (ROI)",
  },
  {
    id: "csc311_ch42_021",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "In a Feasibility Study, ______ feasibility answers the question: 'Will it be used?'",
    options: ["Technical", "Schedule", "Economic", "Operational"],
    correctAnswer: 3,
    explanation: "Operational: Will it be used?",
  },
  {
    id: "csc311_ch42_022",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "In a Feasibility Study, Schedule feasibility asks if the system can be built ______.",
    options: [
      "on time",
      "under budget",
      "without bugs",
      "using existing hardware",
    ],
    correctAnswer: 0,
    explanation: "Schedule: Can we build it on time?",
  },
  {
    id: "csc311_ch42_023",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Gathering requirements through interviews, surveys, and observation is a key activity of the ______ phase.",
    options: ["Analysis", "Design", "Implementation", "Maintenance"],
    correctAnswer: 0,
    explanation:
      "Analysis Key Activities: Gather requirements through interviews, surveys, and observation.",
  },
  {
    id: "csc311_ch42_024",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "During the Analysis phase, studying the current system generates the ______ model.",
    options: ["to-be", "physical", "as-is", "logical"],
    correctAnswer: 2,
    explanation:
      "Analysis Key Activities: ... Study the current system ('as-is' model).",
  },
  {
    id: "csc311_ch42_025",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "During the Analysis phase, modeling and analyzing business processes is performed.",
    options: ["True", "I don't know", "Maybe", "False"],
    correctAnswer: 0,
    explanation:
      "True. Analysis Key Activities: ... Model and analyze business processes.",
  },
  {
    id: "csc311_ch42_026",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "During the Analysis phase, defining the new system's logical requirements creates the ______ model.",
    options: ["as-is", "to-be", "physical", "iterative"],
    correctAnswer: 1,
    explanation:
      "Analysis Key Activities: ... Define the new system's logical requirements ('to-be' model).",
  },
  {
    id: "csc311_ch42_027",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "In the Design phase, Logical Design determines ______ the system will do.",
    options: ["how", "when", "what", "where"],
    correctAnswer: 2,
    explanation:
      "Design Key Activities: Logical Design: What the system will do.",
  },
  {
    id: "csc311_ch42_028",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Data flows and process models are outcomes of ______ Design.",
    options: ["Physical", "Logical", "Iterative", "Feasibility"],
    correctAnswer: 1,
    explanation:
      "Design Key Activities: Logical Design: What the system will do. (Data flows, Process models).",
  },
  {
    id: "csc311_ch42_029",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "In the Design phase, Physical Design determines ______ the system will be built.",
    options: ["why", "what", "how", "who"],
    correctAnswer: 2,
    explanation: "Physical Design: How the system will be built.",
  },
  {
    id: "csc311_ch42_030",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Hardware specs, software choices, database design, and user interface layouts are part of ______ Design.",
    options: ["Logical", "Analysis", "Planning", "Physical"],
    correctAnswer: 3,
    explanation:
      "Physical Design: How the system will be built. (Hardware specs, software choices, database design, user interface layouts).",
  },
  {
    id: "csc311_ch42_031",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Creating a ______ blueprint is a key activity in the Design phase.",
    options: ["technical", "business", "financial", "management"],
    correctAnswer: 0,
    explanation: "Design Key Activities: ... Create a technical blueprint.",
  },
  {
    id: "csc311_ch42_032",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "System Construction, which involves coding/programming the system, takes place in the ______ phase.",
    options: ["Analysis", "Design", "Implementation", "Testing"],
    correctAnswer: 2,
    explanation:
      "Implementation Key Activities: System Construction: Coding/programming the system.",
  },
  {
    id: "csc311_ch42_033",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "During Installation/Deployment, a ______ approach means the old and new systems run simultaneously.",
    options: ["Pilot", "Parallel", "Phased", "Plunge"],
    correctAnswer: 1,
    explanation:
      "Installation/Deployment: Parallel: Old and new run simultaneously.",
  },
  {
    id: "csc311_ch42_034",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "During Installation/Deployment, launching the system in one department first is known as a ______ approach.",
    options: ["Phased", "Parallel", "Plunge", "Pilot"],
    correctAnswer: 3,
    explanation:
      "Installation/Deployment: Pilot: Launch in one department first.",
  },
  {
    id: "csc311_ch42_035",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Rolling out modules one at a time is known as a ______ deployment approach.",
    options: ["Parallel", "Phased", "Pilot", "Direct Cutover"],
    correctAnswer: 1,
    explanation:
      "Installation/Deployment: Phased: Roll out modules one at a time.",
  },
  {
    id: "csc311_ch42_036",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "An immediate switch to the new system is known as a Direct Cutover or ______ deployment.",
    options: ["Plunge", "Parallel", "Phased", "Pilot"],
    correctAnswer: 0,
    explanation:
      "Installation/Deployment: Plunge (Direct Cutover): Immediate switch.",
  },
  {
    id: "csc311_ch42_037",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Training users and creating documentation are key activities performed during the Design phase.",
    options: ["True", "I don't know", "False", "Maybe"],
    correctAnswer: 2,
    explanation:
      "False. Training users and creating documentation are Key Activities of the Implementation phase.",
  },
  {
    id: "csc311_ch42_038",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "In the Testing phase, ______ Testing focuses on individual components or modules.",
    options: ["Integration", "System", "User Acceptance", "Unit"],
    correctAnswer: 3,
    explanation: "Testing: Unit Testing: Individual components/modules.",
  },
  {
    id: "csc311_ch42_039",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "In the Testing phase, ______ Testing checks the interfaces between modules.",
    options: ["System", "Integration", "Unit", "User Acceptance"],
    correctAnswer: 1,
    explanation: "Testing: Integration Testing: Interfaces between modules.",
  },
  {
    id: "csc311_ch42_040",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "In the Testing phase, ______ Testing validates the complete integrated system.",
    options: ["Unit", "Integration", "User Acceptance", "System"],
    correctAnswer: 3,
    explanation: "Testing: System Testing: Complete integrated system.",
  },
  {
    id: "csc311_ch42_041",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The abbreviation UAT stands for ______.",
    options: [
      "Universal Application Testing",
      "User Acceptance Testing",
      "Unit and Algorithm Testing",
      "Uniform Access Testing",
    ],
    correctAnswer: 1,
    explanation: "User Acceptance Testing (UAT): End-user validatio[n].",
  },
  {
    id: "csc311_ch42_042",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "End-user validation occurs during ______.",
    options: [
      "Unit Testing",
      "Integration Testing",
      "System Testing",
      "User Acceptance Testing (UAT)",
    ],
    correctAnswer: 3,
    explanation: "User Acceptance Testing (UAT): End-user validatio[n].",
  },
  {
    id: "csc311_ch42_043",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Fixing bugs and errors is a key activity in the ______ phase.",
    options: ["Design", "Implementation", "Maintenance", "Planning"],
    correctAnswer: 2,
    explanation: "Maintenance Key Activities: Fixing bugs and errors.",
  },
  {
    id: "csc311_ch42_044",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Making minor and major enhancements occurs during the Maintenance phase.",
    options: ["False", "Maybe", "True", "I don't know"],
    correctAnswer: 2,
    explanation:
      "True. Maintenance Key Activities: ... Making minor and major enhancements.",
  },
  {
    id: "csc311_ch42_045",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Adapting the system to new business needs or technologies is part of the ______ phase.",
    options: ["Planning", "Maintenance", "Design", "Analysis"],
    correctAnswer: 1,
    explanation:
      "Maintenance Key Activities: ... Adapting the system to new business needs or technologies.",
  },
  {
    id: "csc311_ch42_046",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The ______ phase is often the longest and most costly phase of the SDLC.",
    options: ["Implementation", "Design", "Maintenance", "Analysis"],
    correctAnswer: 2,
    explanation:
      "Maintenance... This is often the longest and most costly phase.",
  },
  {
    id: "csc311_ch42_047",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Successful systems require ______ involvement.",
    options: ["user", "zero management", "only IT", "third-party"],
    correctAnswer: 0,
    explanation:
      "The Role of Users and Managers in the SDLC: Successful systems require user involvement.",
  },
  {
    id: "csc311_ch42_048",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "In the SDLC, the role of providing requirements, participating in UAT, and giving feedback belongs to the ______.",
    options: ["Managers", "Users", "IT Developers", "System Analysts"],
    correctAnswer: 1,
    explanation:
      "Users: Provide requirements, participate in testing (UAT), and give feedback.",
  },
  {
    id: "csc311_ch42_049",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "In the SDLC, the role of securing funding and championing the project belongs to the ______.",
    options: ["Managers", "Users", "Programmers", "Database Administrators"],
    correctAnswer: 0,
    explanation:
      "Managers: Secure funding, champion the project, make strategic decisions...",
  },
  {
    id: "csc311_ch42_050",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Managing organizational change is primarily the responsibility of users during the SDLC.",
    options: ["I don't know", "Maybe", "False", "True"],
    correctAnswer: 2,
    explanation:
      "False. Managers are the ones who manage organizational change, not the users. ('Managers: ... manage organizational change.')",
  },
  {
    id: "csc311_ch42_051",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "A key principle of the SDLC is that IT builds the system, but the ______ owns it.",
    options: ["government", "project manager", "business", "end-user alone"],
    correctAnswer: 2,
    explanation: "IT builds the system, but the business owns it.",
  },
  {
    id: "csc311_ch42_052",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The summary states that the SDLC is a structured process with ______ phases, though earlier slides detail 6 core phases.",
    options: ["five", "three", "seven", "eight"],
    correctAnswer: 0,
    explanation:
      "SUMMARY: The SDLC is a structured process with five phases: Planning, Analysis, Design, Implementation, and Maintenance. (Note: Testing is grouped into Implementation/Maintenance in some 5-phase models, though the 6 Core Phases slide listed Testing separately).",
  },
  {
    id: "csc311_ch42_053",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "According to the summary, each phase of the SDLC has specific activities and ______.",
    options: ["deliverables", "roadblocks", "budgets", "schedules"],
    correctAnswer: 0,
    explanation: "Each phase has specific activities and deliverables.",
  },
  {
    id: "csc311_ch42_054",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The Planning phase fundamentally answers the question: '______?'",
    options: ["When", "How", "What", "Why"],
    correctAnswer: 3,
    explanation: "Planning answers 'Why?'",
  },
  {
    id: "csc311_ch42_055",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The Analysis phase fundamentally answers the question: '______?'",
    options: ["How", "What", "Why", "Who"],
    correctAnswer: 1,
    explanation: "Analysis answers 'What?'",
  },
  {
    id: "csc311_ch42_056",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The Design phase fundamentally answers the question: '______?'",
    options: ["How", "Why", "When", "What"],
    correctAnswer: 0,
    explanation: "Design answers 'How?'",
  },
  {
    id: "csc311_ch42_057",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "User and Manager involvement is critical for the success of the SDLC.",
    options: ["True", "Maybe", "I don't know", "False"],
    correctAnswer: 0,
    explanation:
      "True. SUMMARY: User and Manager involvement is critical for success.",
  },
  {
    id: "csc311_ch42_058",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "In the Spiral model, the cyclical loops consist of planning, risk analysis, engineering, and ______.",
    options: ["evaluation", "deployment", "marketing", "budgeting"],
    correctAnswer: 0,
    explanation:
      "Spiral: A risk-driven model that cycles through phases of planning, risk analysis, engineering, and evaluation in iterative loops.",
  },
  {
    id: "csc311_ch42_059",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "A core objective of learning about the SDLC is to explain the main tasks needed to prepare for the establishment of a new ______.",
    options: [
      "hardware component",
      "information system",
      "business department",
      "office building",
    ],
    correctAnswer: 1,
    explanation:
      "Objectives: explain the main tasks that need to be undertaken in preparing for the establishment of a new information system in terms of the systems development lifecycle...",
  },
  {
    id: "csc311_ch42_060",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Which of these SDLC models strictly forbids moving to the next phase until the current one is entirely finished?",
    options: ["Iterative", "Agile", "Spiral", "Waterfall"],
    correctAnswer: 3,
    explanation:
      "Waterfall: A linear, sequential approach where each phase must be fully completed before the next begins.",
  },
  {
    id: "csc311_ch42_061",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "The 'to-be' model defines the ______ requirements of the new system.",
    options: ["physical", "budgetary", "logical", "operational"],
    correctAnswer: 2,
    explanation:
      "Define the new system's logical requirements ('to-be' model).",
  },
  {
    id: "csc311_ch42_062",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Which of the following describes the Physical Design stage?",
    options: [
      "Identifying the project",
      "Studying the current as-is system",
      "Determining hardware specs and software choices",
      "Creating data flows and process models",
    ],
    correctAnswer: 2,
    explanation:
      "Physical Design: How the system will be built. (Hardware specs, software choices, database design, user interface layouts).",
  },
  {
    id: "csc311_ch42_063",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "During the SDLC, User Acceptance Testing (UAT) is performed by the developers.",
    options: ["I don't know", "True", "Maybe", "False"],
    correctAnswer: 3,
    explanation:
      "False. User Acceptance Testing (UAT) is end-user validation, and Users 'participate in testing (UAT)'.",
  },
  {
    id: "csc311_ch42_064",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "Three items often evaluated during a Feasibility Study are: (1) Technical (2) Economic (3) ______",
    options: ["Logical", "Iterative", "Operational", "Agile"],
    correctAnswer: 2,
    explanation:
      "Conduct a Feasibility Study: Technical... Economic... Operational... Schedule...",
  },
  {
    id: "csc311_ch42_065",
    course: "CSC 311",
    chapter: "Chapter 4_2",
    text: "A technical blueprint is finalized right before system construction begins, typically during the ______ phase.",
    options: ["Design", "Testing", "Planning", "Analysis"],
    correctAnswer: 0,
    explanation:
      "Design Key Activities: ... Create a technical blueprint. (Implementation follows Design).",
  },
];

export default csc311Chapter4_2;
