import { QuestionV2 } from "@/lib/quiz-types";

const csc311Chapter2: QuestionV2[] = [
  {
    id: "csc311_m2_001",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Data consists of raw facts, and when organized may be transformed into ______.",
    options: ["knowledge bases", "information", "entities", "data marts"],
    correctAnswer: 1,
    explanation:
      "Data consists of raw facts, and when organized may be transformed into information.",
  },
  {
    id: "csc311_m2_002",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A ______ is a collection of data organized to meet users’ needs.",
    options: ["Database", "Record", "Subschema", "Data dictionary"],
    correctAnswer: 0,
    explanation:
      "Database: A collection of data organized to meet users’ needs.",
  },
  {
    id: "csc311_m2_003",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A group of programs that manipulate the database and provide an interface between the database and the user is called a ______.",
    options: [
      "Data model",
      "Database management system (DBMS)",
      "Structured query language (SQL)",
      "Logical access path",
    ],
    correctAnswer: 1,
    explanation:
      "Database management system (DBMS): A group of programs that manipulate the database and provide an interface between the database and the user.",
  },
  {
    id: "csc311_m2_004",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In the hierarchy of data, a database is a collection of integrated and related ______.",
    options: ["fields", "characters", "records", "files"],
    correctAnswer: 3,
    explanation:
      "Terminology: Database - A collection of integrated and related files.",
  },
  {
    id: "csc311_m2_005",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A file is a collection of integrated and related databases.",
    options: ["True", "False", "I don't know", "Maybe"],
    correctAnswer: 1,
    explanation:
      "False. A File is a collection of related records, not related databases.",
  },
  {
    id: "csc311_m2_006",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A record is defined as a collection of related ______.",
    options: ["files", "fields", "characters", "attributes"],
    correctAnswer: 1,
    explanation: "Record: A collection of related fields.",
  },
  {
    id: "csc311_m2_007",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A field is a group of ______.",
    options: ["records", "characters", "files", "entities"],
    correctAnswer: 1,
    explanation: "Field: A group of characters.",
  },
  {
    id: "csc311_m2_008",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "The basic building block of information is a ______, represented by a byte.",
    options: ["Character", "Field", "Record", "Key"],
    correctAnswer: 0,
    explanation:
      "Character: Basic building block of information, represented by a byte.",
  },
  {
    id: "csc311_m2_009",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "An ______ is a generalized class of people, places, or things (objects) for which data are collected, stored, and maintained.",
    options: ["Attribute", "Entity", "Object-relation", "Access path"],
    correctAnswer: 1,
    explanation:
      "Entity: A generalized class of people, places, or things (objects) for which data are collected, stored, and maintained.",
  },
  {
    id: "csc311_m2_010",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Customer name and Employee name are examples of an ______.",
    options: ["Attribute", "Entity", "Object", "Interface"],
    correctAnswer: 0,
    explanation:
      "Attribute: A characteristic of an entity; something the entity is identified by. E.g., Customer name, Employee name.",
  },
  {
    id: "csc311_m2_011",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A field or set of fields in a record that is used to uniquely identify the record is called a ______.",
    options: ["Key", "Schema", "Data model", "Subschema"],
    correctAnswer: 0,
    explanation:
      "Keys: A field or set of fields in a record that is used to identify the record... uniquely identifies the record.",
  },
  {
    id: "csc311_m2_012",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In the traditional approach, a pool of related data is shared by multiple application programs.",
    options: ["I don't know", "Maybe", "True", "False"],
    correctAnswer: 3,
    explanation:
      "False. In the traditional approach, separate files are created and stored for each application program. The database approach shares a pool of related data.",
  },
  {
    id: "csc311_m2_013",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Data ______ is the duplication of data in separate files.",
    options: ["integrity", "independence", "redundancy", "concurrency"],
    correctAnswer: 2,
    explanation: "Data redundancy: Duplication of data in separate files.",
  },
  {
    id: "csc311_m2_014",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "The degree to which the data in any one file is accurate refers to data ______.",
    options: ["integrity", "redundancy", "dependence", "mining"],
    correctAnswer: 0,
    explanation:
      "Lack of data integrity: The degree to which the data in any one file is accurate.",
  },
  {
    id: "csc311_m2_015",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "______ is a situation in which program and data organized for one application are incompatible with programs and data organized differently for another application.",
    options: [
      "Data redundancy",
      "Concurrency control",
      "Program-data dependence",
      "Data extraction",
    ],
    correctAnswer: 2,
    explanation:
      "Program-data dependence: A situation in which program and data organized for one application are incompatible with programs and data organized differently for another application.",
  },
  {
    id: "csc311_m2_016",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In the ______ approach, a pool of related data is shared by multiple application programs.",
    options: ["Traditional", "Database", "Hierarchical", "Network"],
    correctAnswer: 1,
    explanation:
      "The database approach... A pool of related data is shared by multiple application programs.",
  },
  {
    id: "csc311_m2_017",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "One disadvantage of the database approach is the relatively high cost of purchasing and operating a DBMS in a ______ operating environment.",
    options: ["mainframe", "distributed", "personal computer", "cloud"],
    correctAnswer: 0,
    explanation:
      "Disadvantages: Relatively high cost of purchasing and operating a DBMS in a mainframe operating environment.",
  },
  {
    id: "csc311_m2_018",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Easier modification and updating is an advantage of the Database Approach.",
    options: ["Maybe", "I don't know", "False", "True"],
    correctAnswer: 3,
    explanation:
      "True. Advantages of the database approach include: Easier modification and updating, Reduced data redundancy, and Improved data integrity.",
  },
  {
    id: "csc311_m2_019",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A way of organizing data in which the logical database design is altered so that certain data entities are combined is called ______ data redundancy.",
    options: ["traditional", "unplanned", "planned", "logical"],
    correctAnswer: 2,
    explanation:
      "Planned data redundancy: A way of organizing data in which the logical database design is altered so that certain data entities are combined.",
  },
  {
    id: "csc311_m2_020",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A ______ is a map or diagram of entities and their relationships.",
    options: [
      "schema blueprint",
      "data model",
      "subschema",
      "concurrency path",
    ],
    correctAnswer: 1,
    explanation:
      "Data model: A map or diagram of entities and their relationships.",
  },
  {
    id: "csc311_m2_021",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Enterprise data modeling is data modeling done at the level of the entire ______.",
    options: ["application", "subschema", "department", "organization"],
    correctAnswer: 3,
    explanation:
      "Enterprise data modeling: Data modeling done at the level of the entire organization.",
  },
  {
    id: "csc311_m2_022",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Entity-relationship (ER) diagrams use basic ______ symbols to show the organization of and relationships between data.",
    options: ["alphanumeric", "graphical", "mathematical", "spatial"],
    correctAnswer: 1,
    explanation:
      "Entity-relationship (ER) diagrams: A data model that uses basic graphical symbols to show the organization of and relationships between data.",
  },
  {
    id: "csc311_m2_023",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In an ER Diagram, a 1:N notation signifies a ______ relationship.",
    options: ["one-to-one", "many-to-many", "one-to-many", "many-to-one"],
    correctAnswer: 2,
    explanation: "Example ER Diagram specifies '1:N one-to-many relationship'.",
  },
  {
    id: "csc311_m2_024",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "The ______ database model is a data model in which data are organized in a top-down, or inverted tree structure.",
    options: ["Relational", "Hierarchical", "Network", "Object-oriented"],
    correctAnswer: 1,
    explanation:
      "Hierarchical database model: A data model in which data are organized in a top-down, or inverted tree structure.",
  },
  {
    id: "csc311_m2_025",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "The ______ data model is an expansion of the hierarchical database model with an owner-member relationship in which a member may have many owners.",
    options: ["Network", "Spatial", "Relational", "Hierarchical"],
    correctAnswer: 0,
    explanation:
      "Network data model: An expansion of the hierarchical database model with an owner-member relationship in which a member may have many owners.",
  },
  {
    id: "csc311_m2_026",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "The Relational data model is the most widely used model in modern database systems like MySQL and Oracle.",
    options: ["Maybe", "True", "False", "I don't know"],
    correctAnswer: 1,
    explanation:
      "True. All data elements are placed in two-dimensional tables... It is the most widely used model in modern dtabase system (MySQI, SQL, Oracle).",
  },
  {
    id: "csc311_m2_027",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In a relational data model, all data elements are placed in two-dimensional tables called ______.",
    options: ["schemas", "relations", "entities", "subschemas"],
    correctAnswer: 1,
    explanation:
      "Relational data model: This is a way of organizing and structuring data using tables calles relation... All data elements are placed in two-dimensional tables, called relations.",
  },
  {
    id: "csc311_m2_028",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In relational database terminology, data manipulation that eliminates rows according to certain criteria is called ______.",
    options: ["Joining", "Linking", "Selecting", "Projecting"],
    correctAnswer: 2,
    explanation:
      "Selecting: Data manipulation that eliminates rows according to certain criteria.",
  },
  {
    id: "csc311_m2_029",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In relational database terminology, data manipulation that eliminates columns in a table is called ______.",
    options: ["Projecting", "Selecting", "Joining", "Extracting"],
    correctAnswer: 0,
    explanation:
      "Projecting: Data manipulation that eliminates columns in a table.",
  },
  {
    id: "csc311_m2_030",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Data manipulation that combines two or more tables is called ______.",
    options: ["Projecting", "Selecting", "Joining", "Mapping"],
    correctAnswer: 2,
    explanation: "Joining: Data manipulation that combines two or more tables.",
  },
  {
    id: "csc311_m2_031",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Relating tables in a relational database together is referred to as ______.",
    options: ["Joining", "Selecting", "Linking", "Schema design"],
    correctAnswer: 2,
    explanation: "Linked: Relating tables in a relational database together.",
  },
  {
    id: "csc311_m2_032",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A description of the entire database, or the overall logical structure of the blueprint, is called a ______.",
    options: ["Schema", "Subschema", "Data Dictionary", "Data Model"],
    correctAnswer: 0,
    explanation:
      "Schema: A description of the entire database. i.e over logical structure of the entire database(the blueprint of a whole database).",
  },
  {
    id: "csc311_m2_033",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A schema is a subset of the database schema accessible to a particular user.",
    options: ["False", "True", "I don't know", "Maybe"],
    correctAnswer: 0,
    explanation:
      "False. A schema is the description of the ENTIRE database. A Subschema is a subset of the database schema accessible to a particular user.",
  },
  {
    id: "csc311_m2_034",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A ______ is a file that contains a description of a subset of the database and identifies which users can perform modifications on those data items.",
    options: ["Schema", "Data Dictionary", "Subschema", "Directory"],
    correctAnswer: 2,
    explanation:
      "Subschema: A file that contains a description of a subset of the database and identifies which users can perform modifications on the data items in that subset.",
  },
  {
    id: "csc311_m2_035",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A detailed description of all data used in the database, including what each data means and where it is stored, is found in the ______.",
    options: [
      "Schema blueprint",
      "Data Dictionary",
      "Network model",
      "Subschema",
    ],
    correctAnswer: 1,
    explanation:
      "Data Dictionary: A detailed description of all data used in the database. It describes metadata that is data about data...",
  },
  {
    id: "csc311_m2_036",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Metadata can be simply defined as ______.",
    options: [
      "data about subschemas",
      "data about data",
      "data about hardware",
      "data about network paths",
    ],
    correctAnswer: 1,
    explanation:
      "It describes metadata that is data about data, what data exists, what each data means...",
  },
  {
    id: "csc311_m2_037",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "The Logical access path (LAP) occurs when the ______ requires information from the DBMS.",
    options: ["storage device", "operating system", "hardware", "Application"],
    correctAnswer: 3,
    explanation:
      "Logical access path (LAP): Application requires information from the DBMS.",
  },
  {
    id: "csc311_m2_038",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "The Physical access path (PAP) is when the DBMS accesses a ______ to retrieve data.",
    options: [
      "subschema",
      "storage device",
      "data dictionary",
      "logical schema",
    ],
    correctAnswer: 1,
    explanation:
      "Physical access path (PAP): DBMS accesses a storage device to retrieve data.",
  },
  {
    id: "csc311_m2_039",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Structured Query Language (SQL) was invented at IBM’s Almaden Research Centre in the 1990s.",
    options: ["I don't know", "True", "False", "Maybe"],
    correctAnswer: 2,
    explanation:
      "False. SQL was “Invented” at IBM’s Almaden Research Centre (San Jose, CA) in the 1970s.",
  },
  {
    id: "csc311_m2_040",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In the SQL query `SELECT * FROM EMPLOYEE`, the asterisk (*) means to select all ______.",
    options: ["tables", "columns", "databases", "subschemas"],
    correctAnswer: 1,
    explanation: "E.g., Select all (“*”) columns from the EMPLOYEE table...",
  },
  {
    id: "csc311_m2_041",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "______ is a collection of instructions and commands used to define and describe data and data relationships in a specific database.",
    options: [
      "Data Manipulation Language (DML)",
      "Data Definition Language (DDL)",
      "Transaction Control Language (TCL)",
      "Data Control Language (DCL)",
    ],
    correctAnswer: 1,
    explanation:
      "Data Definition Language (DDL): A collection of instructions and commands used to define and describe data and data relationships in a specific database.",
  },
  {
    id: "csc311_m2_042",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Creating database objects, altering database structures, and truncating tables are functions of ______.",
    options: ["DDL", "DML", "DCL", "TCL"],
    correctAnswer: 0,
    explanation:
      "Functions [of DDL]: create database objects, alter database structures, drop/delete objects, rename objects, truncate tables.",
  },
  {
    id: "csc311_m2_043",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "______ is a method of dealing with a situation in which two or more people need to access the same record in a database at the same time.",
    options: [
      "Spatial data analysis",
      "Data redundancy",
      "Concurrency control",
      "Schema modification",
    ],
    correctAnswer: 2,
    explanation:
      "Concurrency control: A method of dealing with a situation in which two or more people need to access the same record in a database at the same time.",
  },
  {
    id: "csc311_m2_044",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "The commands that are used to manipulate the data in a database fall under ______.",
    options: [
      "Data Definition Language (DDL)",
      "Data Control Language (DCL)",
      "Transaction Control Language (TCL)",
      "Data Manipulation Language (DML)",
    ],
    correctAnswer: 3,
    explanation:
      "Data manipulation language (DML): The commands that are used to manipulate the data in a database.",
  },
  {
    id: "csc311_m2_045",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Microsoft Access 98 and Lotus Approach 98 are examples of popular ______.",
    options: [
      "data warehouses",
      "Database Management Systems for End Users",
      "Object-Relational systems",
      "Distributed databases",
    ],
    correctAnswer: 1,
    explanation:
      "Popular Database Management Systems for End Users: Microsoft Access 98, Lotus Approach 98, Inprise (formerly Borland) dBASE.",
  },
  {
    id: "csc311_m2_046",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A Distributed Database is one where actual data may be spread across several smaller databases connected via telecommunications devices.",
    options: ["Maybe", "False", "True", "I don't know"],
    correctAnswer: 2,
    explanation:
      "True. Distributed database... A database in which the actual data may be spread across several smaller databases connected via telecommunications devices.",
  },
  {
    id: "csc311_m2_047",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A ______ is a relational database management system designed specifically to support management decision making.",
    options: [
      "data dictionary",
      "subschema",
      "data warehouse",
      "concurrency control system",
    ],
    correctAnswer: 2,
    explanation:
      "Data warehouse: A relational database management system designed specifically to support management decision making.",
  },
  {
    id: "csc311_m2_048",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A data warehouse is considered the current evolution of ______.",
    options: [
      "Decision Support Systems (DSSs)",
      "Object-Relational Database Management Systems (ORDBMS)",
      "Data Control Languages (DCL)",
      "Hierarchical database models",
    ],
    correctAnswer: 0,
    explanation:
      "Data warehouse... Current evolution of Decision Support Systems (DSSs).",
  },
  {
    id: "csc311_m2_049",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A ______ is a subset of a data warehouse designed for small and medium-size businesses or departments within larger companies.",
    options: [
      "data subschema",
      "data mart",
      "spatial database",
      "hypertext model",
    ],
    correctAnswer: 1,
    explanation:
      "Data mart: A subset of a data warehouse for small and medium-size businesses or departments within larger companies.",
  },
  {
    id: "csc311_m2_050",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Before you build a customer data warehouse, the very first step is to sharply define your ______.",
    options: [
      "software vendor",
      "ER diagrams",
      "subschemas",
      "goals and objectives",
    ],
    correctAnswer: 3,
    explanation:
      "Designing a Customer Data Warehouse: Sharply define your goals and objectives before you build the warehouse.",
  },
  {
    id: "csc311_m2_051",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Data mining provides top-down, query-driven analysis.",
    options: ["I don't know", "True", "False", "Maybe"],
    correctAnswer: 2,
    explanation:
      "False. Data mining provides bottom-up, discovery-driven analysis. Data warehouse and OLAP provide top-down, query-driven analysis.",
  },
  {
    id: "csc311_m2_052",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "The automated discovery of patterns and relationships in a data warehouse is known as ______.",
    options: ["OLAP", "Data mining", "Data extraction", "Concurrency control"],
    correctAnswer: 1,
    explanation:
      "Data mining: The automated discovery of patterns and relationships in a data warehouse.",
  },
  {
    id: "csc311_m2_053",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Which of the following is an application of data mining?",
    options: [
      "Market basket analysis",
      "Designing an ER diagram",
      "Writing DDL statements",
      "Physical access path routing",
    ],
    correctAnswer: 0,
    explanation:
      "Data mining applications: Market segmentation, Customer queries, Fraud detection, Direct marketing, Market basket analysis, Trend analysis.",
  },
  {
    id: "csc311_m2_054",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "______ provides access to multidimensional databases providing managerially useful display techniques.",
    options: [
      "DCL",
      "ODBC",
      "On-line analytic processing (OLAP)",
      "Data dictionary",
    ],
    correctAnswer: 2,
    explanation:
      "On-line analytic processing (OLAP): Access to multidimensional databases providing managerially useful display techniques.",
  },
  {
    id: "csc311_m2_055",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Data warehouse and OLAP are known to provide ______, query-driven analysis.",
    options: ["bottom-up", "top-down", "horizontal", "spatial"],
    correctAnswer: 1,
    explanation:
      "Data warehouse and OLAP: Provides top-down, query-driven analysis.",
  },
  {
    id: "csc311_m2_056",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A set of standards that ensures software written to comply with these standards can be used with any compliant database is known as ______.",
    options: ["ODBC", "ORDBMS", "OLAP", "DDL"],
    correctAnswer: 0,
    explanation:
      "Open database connectivity (ODBC): A set of standards that ensures software written to comply with these standards can be used with any ODBC-compliant database.",
  },
  {
    id: "csc311_m2_057",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "An Object-relational database management system (ORDBMS) is capable of manipulating ______, video, and graphical data.",
    options: ["only numeric", "audio", "mainframe", "unstructured code"],
    correctAnswer: 1,
    explanation:
      "Object-relational database management system (ORDBMS): A DBMS capable of manipulating audio, video, and graphical data.",
  },
  {
    id: "csc311_m2_058",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "______ allows users to search and manipulate alphanumeric data in an unstructured way.",
    options: ["Hypertext", "Spatial data", "Network model", "Data mart"],
    correctAnswer: 0,
    explanation:
      "Hypertext: Users can search and manipulate alphanumeric data in an unstructured way.",
  },
  {
    id: "csc311_m2_059",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "______ allows businesses to search and manipulate multimedia forms of data.",
    options: [
      "Hypertext",
      "Hypermedia",
      "Concurrency control",
      "Data Definition Language",
    ],
    correctAnswer: 1,
    explanation:
      "Hypermedia: Allows businesses to search and manipulate multimedia forms of data.",
  },
  {
    id: "csc311_m2_060",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "______ technology uses an object-relational database to store and access data according to the location it describes.",
    options: [
      "Spatial data",
      "Hypertext",
      "Network data",
      "Telecommunications",
    ],
    correctAnswer: 0,
    explanation:
      "Spatial data technology: Use of an object-relational database to store and access data according to the location it describes and to permit spatial queries and analysis.",
  },
  {
    id: "csc311_m2_061",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In the example of the hierarchy of data, the letter 'F' represented in ASCII is an example of a ______.",
    options: ["File", "Record", "Character", "Database"],
    correctAnswer: 2,
    explanation:
      "Hierarchy of data Example... 1000100 (Letter ‘F’ in ASCII) corresponds to Characters(bytes).",
  },
  {
    id: "csc311_m2_062",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Increased vulnerability is considered an advantage of the Database Approach.",
    options: ["Maybe", "I don't know", "False", "True"],
    correctAnswer: 2,
    explanation:
      "False. Increased vulnerability is listed under Disadvantages of the database approach.",
  },
  {
    id: "csc311_m2_063",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Which of the following is NOT a feature of a Data Dictionary?",
    options: [
      "Provide a standard definition of terms",
      "Eliminate the need for all database software",
      "Simplify database modification",
      "Reduce data redundancy",
    ],
    correctAnswer: 1,
    explanation:
      "Data Dictionary Features include: Provide a standard definition of terms, Simplify database modification, Reduce data redundancy. Eliminating software is not a feature.",
  },
  {
    id: "csc311_m2_064",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A Data Dictionary can assist programmers in designing and writing programs.",
    options: ["I don't know", "Maybe", "False", "True"],
    correctAnswer: 3,
    explanation:
      "True. Data Dictionary Features: Assist programmers in designing and writing programs.",
  },
  {
    id: "csc311_m2_065",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Data mining provides ______, discovery-driven analysis.",
    options: ["top-down", "bottom-up", "horizontal", "schematic"],
    correctAnswer: 1,
    explanation: "Data mining: Provides bottom-up, discovery-driven analysis.",
  },
  {
    id: "csc311_m2_066",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In the context of SQL categories, TCL stands for ______.",
    options: [
      "Table Creation Language",
      "Transaction Control Language",
      "Test Case Language",
      "Transfer Configuration Language",
    ],
    correctAnswer: 1,
    explanation: "Categories of sql: ... TRANSACTION CONTROL LANGUAGE.",
  },
  {
    id: "csc311_m2_067",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In the context of SQL categories, DCL stands for ______.",
    options: [
      "Data Creation Language",
      "Database Configuration Language",
      "Data Control Language",
      "Digital Certificate Language",
    ],
    correctAnswer: 2,
    explanation: "Categories of sql: ... DATA CONTROL LANGUAGE.",
  },
  {
    id: "csc311_m2_068",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A subschema is a subset of the database schema accessible to a particular user.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "True. A subschema is a subset of the database schema acccesible to a particular user (user-specific view of the database).",
  },
  {
    id: "csc311_m2_069",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In a Relational Data Model, tables are called ______.",
    options: ["schemas", "subschemas", "relations", "hierarchies"],
    correctAnswer: 2,
    explanation:
      "Relational data model: This is a way of organizing and structuring data using tables calles relation.",
  },
  {
    id: "csc311_m2_070",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In a relational data model, columns can be eliminated using a manipulation called ______.",
    options: ["Joining", "Selecting", "Projecting", "Truncating"],
    correctAnswer: 2,
    explanation:
      "Projecting: Data manipulation that eliminates columns in a table.",
  },
  {
    id: "csc311_m2_071",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Which of the following is NOT an advantage of the database approach?",
    options: [
      "Standardization of data access",
      "Increased vulnerability",
      "Better overall protection of the data",
      "Improved strategic use of corporate data",
    ],
    correctAnswer: 1,
    explanation:
      "Increased vulnerability is listed under Disadvantages, not Advantages.",
  },
  {
    id: "csc311_m2_072",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In the traditional approach, program and data organized for one application are sometimes incompatible with those organized differently for another application. This is called ______.",
    options: [
      "Data integrity failure",
      "Program-data dependence",
      "Data redundancy",
      "Concurrency error",
    ],
    correctAnswer: 1,
    explanation:
      "Program-data dependence: A situation in which program and data organized for one application are incompatible with programs and data organized differently for another application.",
  },
  {
    id: "csc311_m2_073",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "DBMS selection criteria include Database size, Performance, Integration, Cost, Features, The vendor, and ______.",
    options: [
      "Number of current relations",
      "Number of concurrent users",
      "Number of hardware switches",
      "Number of schematic diagrams",
    ],
    correctAnswer: 1,
    explanation:
      "DBMS Selection Criteria: Database size, Number of concurrent users, Performance, Integration, Features, The vendor, Cost.",
  },
  {
    id: "csc311_m2_074",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Which model expands upon the hierarchical database model by allowing a member to have many owners?",
    options: [
      "Network data model",
      "Relational data model",
      "Spatial data model",
      "Linear data model",
    ],
    correctAnswer: 0,
    explanation:
      "Network data model: An expansion of the hierarchical database model with an owner-member relationship in which a member may have many owners.",
  },
  {
    id: "csc311_m2_075",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Data modeling done at the level of the entire organization is called ______.",
    options: [
      "Macro data modeling",
      "Global data modeling",
      "Enterprise data modeling",
      "Hierarchical data modeling",
    ],
    correctAnswer: 2,
    explanation:
      "Enterprise data modeling: Data modeling done at the level of the entire organization.",
  },
  {
    id: "csc311_m2_076",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A Data Dictionary is a detailed description of all data used in the database.",
    options: ["False", "Maybe", "True", "I don't know"],
    correctAnswer: 2,
    explanation:
      "True. Data Dictionary: A detailed description of all data used in the database.",
  },
  {
    id: "csc311_m2_077",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "According to the Data Dictionary example, PARTNO is a data element described as ______.",
    options: [
      "INVENTORY PART NUMER",
      "PERSONNEL ID",
      "PROJECT CODE",
      "CUSTOMER NUMBER",
    ],
    correctAnswer: 0,
    explanation:
      "Data Dictionary example: DATA ELEMENT NAME: PARTNO, DESCRIPTION: INVENTORY PART NUMER.",
  },
  {
    id: "csc311_m2_078",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "The abbreviation for Open Database Connectivity is ______.",
    options: ["OBDC", "ODBC", "ORDBMS", "OLAP"],
    correctAnswer: 1,
    explanation: "Open database connectivity (ODBC).",
  },
  {
    id: "csc311_m2_079",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "The data extraction and cleanup process directly feed data into the ______.",
    options: [
      "Flat files",
      "Data dictionary",
      "Data warehouse",
      "Spatial database",
    ],
    correctAnswer: 2,
    explanation:
      "Based on the schematic: Data extraction process -> Data cleanup process -> Data warehouse.",
  },
  {
    id: "csc311_m2_080",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Flat files and Spreadsheets can serve as inputs for a data extraction process into a data warehouse.",
    options: ["False", "I don't know", "Maybe", "True"],
    correctAnswer: 3,
    explanation:
      "True. The schematic shows Relational databases, Hierarchical databases, Network databases, Flat files, and Spreadsheets all feeding into the Data extraction process.",
  },
  {
    id: "csc311_m2_081",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Which of the following is NOT an application of Data Mining?",
    options: [
      "Fraud detection",
      "Market segmentation",
      "Relational projection",
      "Direct marketing",
    ],
    correctAnswer: 2,
    explanation:
      "Data mining applications include: Market segmentation, Customer queries, Fraud detection, Direct marketing, Market basket analysis, Trend analysis. Relational projection is a database terminology operation, not a data mining application.",
  },
  {
    id: "csc311_m2_082",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Fraud detection is an application of data mining.",
    options: ["Maybe", "True", "False", "I don't know"],
    correctAnswer: 1,
    explanation: "True. Data mining applications: ... Fraud detection ...",
  },
  {
    id: "csc311_m2_083",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Designing a Customer Data Warehouse requires you to measure ______.",
    options: ["ER properties", "hardware heat", "results", "spatial data"],
    correctAnswer: 2,
    explanation: "Designing a Customer Data Warehouse: ... Measure results.",
  },
  {
    id: "csc311_m2_084",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A characteristic of an entity, or something the entity is identified by, is an ______.",
    options: ["Attribute", "Algorithm", "Array", "Access path"],
    correctAnswer: 0,
    explanation:
      "Attribute: A characteristic of an entity; something the entity is identified by.",
  },
  {
    id: "csc311_m2_085",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In the example '005-10-6321 Johns Francine 10-7-65', the 'Johns' part represents a ______.",
    options: ["Key", "File", "Field", "Database"],
    correctAnswer: 2,
    explanation: "It represents a 'Last name field' within a Record.",
  },
  {
    id: "csc311_m2_086",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A situation where summary totals are carried in the data records rather than calculated from elemental data is an example of ______.",
    options: [
      "Program-data dependence",
      "Data mining",
      "Planned data redundancy",
      "Concurrency control",
    ],
    correctAnswer: 2,
    explanation:
      "Planned data redundancy... Summary totals are carried in the data records rather than calculated from elemental data.",
  },
  {
    id: "csc311_m2_087",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A DBMS capable of manipulating audio, video, and graphical data is known as an ______.",
    options: ["ORDBMS", "ODBC", "OLAP", "ER Model"],
    correctAnswer: 0,
    explanation:
      "Object-relational database management system (ORDBMS): A DBMS capable of manipulating audio, video, and graphical data.",
  },
  {
    id: "csc311_m2_088",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Spatial data technology is completely unable to handle queries relating to physical locations.",
    options: ["True", "Maybe", "I don't know", "False"],
    correctAnswer: 3,
    explanation:
      "False. Spatial data technology: Use of an object-relational database to store and access data according to the location it describes and to permit spatial queries and analysis.",
  },
  {
    id: "csc311_m2_089",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "If multiple application programs access a shared pool of related data rather than using separate files, this is utilizing the ______.",
    options: [
      "Traditional Approach",
      "Database Approach",
      "Schema-only Approach",
      "Offline Approach",
    ],
    correctAnswer: 1,
    explanation:
      "The database approach... A pool of related data is shared by multiple application programs.",
  },
  {
    id: "csc311_m2_090",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In the context of the DDL description example, `SCHEMA NAME IS XXXX` is followed by specifying the ______.",
    options: ["AUTHOR", "SUBROUTINE", "HARDWARE", "INTERFACE"],
    correctAnswer: 0,
    explanation:
      "SCHEMA DESCRIPTION: SCHEMA NAME IS XXXX, AUTHOR XXXX, DATE XXXX.",
  },
  {
    id: "csc311_m2_091",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "A data mart is essentially a ______ of a data warehouse.",
    options: ["parent", "subset", "hardware component", "logical access path"],
    correctAnswer: 1,
    explanation:
      "Data mart: A subset of a data warehouse for small and medium-size businesses or departments within larger companies.",
  },
  {
    id: "csc311_m2_092",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "In the context of SQL, 'drop/delete objects' is a function of the ______.",
    options: ["DML", "DCL", "DDL", "TCL"],
    correctAnswer: 2,
    explanation:
      "Functions [of DDL]: create database objects, alter database structures, drop/delete objects...",
  },
  {
    id: "csc311_m2_093",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "The abbreviation SQL stands for ______.",
    options: [
      "Sequential Query Language",
      "Structured Query Language",
      "Standard Query Logic",
      "System Query Link",
    ],
    correctAnswer: 1,
    explanation:
      "Structured Query Language (SQL): It is a standard language used to create, manage and manipulate relational database.",
  },
  {
    id: "csc311_m2_094",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "When building a Customer Data Warehouse, after developing a plan, the next mentioned step is to ______.",
    options: [
      "Choose the hardware only",
      "Hire an external agency",
      "Measure results",
      "Delete old data files",
    ],
    correctAnswer: 2,
    explanation:
      "Designing a Customer Data Warehouse... Develop a plan, Measure results.",
  },
  {
    id: "csc311_m2_095",
    course: "CSC 311",
    chapter: "Chapter 2",
    text: "Trend analysis is a recognized application of data mining.",
    options: ["Maybe", "False", "I don't know", "True"],
    correctAnswer: 3,
    explanation: "True. Data mining applications: ... Trend analysis.",
  },
];

export default csc311Chapter2;
