import { QuestionV2 } from "@/lib/quiz-types";

export const csc311Chapter4_1: QuestionV2[] = [
  {
    id: "csc311_lec4_001",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Adoption of ______ has increased in most countries to improve government operations and communication with citizens.",
    options: [
      "e-government",
      "manual record keeping",
      "batch processing",
      "e-commerce",
    ],
    correctAnswer: 0,
    explanation:
      "Adoption of e-government has increased in most countries, but at the same time, the rate of successful adoption and operation varies from country to country.",
  },
  {
    id: "csc311_lec4_002",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The evolution of ICT in the public sector over the past 25 years includes interactions and mutual shaping processes between ICT and inter-related ______ changes.",
    options: ["institutional", "biological", "astronomical", "meteorological"],
    correctAnswer: 0,
    explanation:
      "It presents general trends by examining interactions and mutual shaping processes between ICT evolution and several inter-related institutional changes.",
  },
  {
    id: "csc311_lec4_003",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Blaise Pascal, a French mathematician and philosopher, invented the mechanical calculator so figures could be added to provide ______.",
    options: ["storage", "processing speed", "information", "data algorithms"],
    correctAnswer: 2,
    explanation:
      "JUL 1, 1642: First Calculator - Blaise Pascal, French mathematician and philosopher invented mechanical calculator so figures could be added to provide information.",
  },
  {
    id: "csc311_lec4_004",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Herman Hollerith created a punch card system to tabulate data for the ______ census.",
    options: ["1990", "1890", "1952", "1642"],
    correctAnswer: 1,
    explanation:
      "Aug 30, 1890: Tabulator - Herman Hollerith created a punch card system to tabulate data for the 1890 census.",
  },
  {
    id: "csc311_lec4_005",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Herman Hollerith's company eventually evolved into Microsoft.",
    options: ["Maybe", "I don't know", "False", "True"],
    correctAnswer: 2,
    explanation:
      "False. Hollerith later used the company to provide data processing equipment evolving into International Business Machines (IBM).",
  },
  {
    id: "csc311_lec4_006",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "In 1952, IBM created a punch card system that allowed ______ to read and interpret data from computers by reading hole punchers.",
    options: ["personal computers", "tabulators", "calculators", "mainframes"],
    correctAnswer: 3,
    explanation:
      "May 21, 1952: Punch Cards - IBM Created a punch card system- allowed mainframes to read and interpret data from computers by reading hole punchers.",
  },
  {
    id: "csc311_lec4_007",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "In the mid-1960s, accounting systems were fairly effective in supplying descriptive information but lacked ______.",
    options: ["capacity", "accuracy", "speed", "flexibility"],
    correctAnswer: 0,
    explanation:
      "Mid1960's accounting systems were fairly effective in supplying descriptive information’s but lacked capacity.",
  },
  {
    id: "csc311_lec4_008",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "In the 1970s, Mainframe Computers were used, and systems were connected to business functions like billing, inventory, and ______.",
    options: ["word processing", "data mining", "payroll", "cloud storage"],
    correctAnswer: 2,
    explanation:
      "Systems are connected to business functions (billing, inventory and payroll).",
  },
  {
    id: "csc311_lec4_009",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "By Jan 1, 1980, using Word Processors and Spreadsheets made departments less dependent on the ______ department.",
    options: ["IT", "Finance", "Human Resources", "Operations"],
    correctAnswer: 0,
    explanation:
      "Using Word Processors and Spreadsheets made departments less depend on the IT department.",
  },
  {
    id: "csc311_lec4_010",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "By Jan 1, 1990, ______ became corporate standards.",
    options: [
      "Local Area Networks (LANs)",
      "Wide Area Networks (WANs)",
      "Mainframe computers",
      "Punch card systems",
    ],
    correctAnswer: 1,
    explanation:
      "Jan 1, 1990: Wide Area Networks (WANs) become corporate standards.",
  },
  {
    id: "csc311_lec4_011",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "In the Manual systems era, record keeping was primarily ______-based.",
    options: ["punch card", "mainframe", "digital", "paper"],
    correctAnswer: 3,
    explanation: "Manual systems era – paper-based record keeping.",
  },
  {
    id: "csc311_lec4_012",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "During the Data processing era (1950s–1960s), mainframe computers were widely used for payroll and ______.",
    options: [
      "accounting",
      "artificial intelligence",
      "e-government",
      "remote work",
    ],
    correctAnswer: 0,
    explanation:
      "Data processing era (1950s–1960s) – mainframe computers for payroll and accounting.",
  },
  {
    id: "csc311_lec4_013",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Management Information Systems emerged in the 1970s to provide support for ______ decision-making.",
    options: ["executive", "managerial", "operational", "automated"],
    correctAnswer: 1,
    explanation:
      "Management Information Systems (1970s) – support for managerial decision-making.",
  },
  {
    id: "csc311_lec4_014",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Decision Support Systems emerged in the 1980s as analytical and ______-based systems.",
    options: ["model", "hardware", "manual", "transaction"],
    correctAnswer: 0,
    explanation:
      "Decision Support Systems (1980s) – analytical and model-based systems.",
  },
  {
    id: "csc311_lec4_015",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Enterprise Systems in the 1990s integrated ERP, CRM, and SCM.",
    options: ["True", "Maybe", "I don't know", "False"],
    correctAnswer: 0,
    explanation:
      "True. Enterprise Systems (1990s) – ERP, CRM, SCM integration.",
  },
  {
    id: "csc311_lec4_016",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The Digital and Intelligent Systems era (2000s–present) includes cloud computing, mobile systems, AI, and ______.",
    options: ["punch cards", "mainframes", "big data", "manual ledgers"],
    correctAnswer: 2,
    explanation:
      "Digital and Intelligent Systems (2000s–present) – cloud computing, mobile systems, AI, big data.",
  },
  {
    id: "csc311_lec4_017",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "An Information System provides a ______ mechanism to meet an objective.",
    options: ["hardware", "software", "feedback", "networking"],
    correctAnswer: 2,
    explanation:
      "A set of interrelated components that collect, manipulate, store, and disseminate data and information and provide a feedback mechanism to meet an objective.",
  },
  {
    id: "csc311_lec4_018",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The core components of an IS include hardware, software, data, people, procedures, and ______.",
    options: ["networks", "cloud servers", "algorithms", "policies"],
    correctAnswer: 0,
    explanation:
      "Core components of an IS: Hardware, Software, Data, People, Procedures, Networks.",
  },
  {
    id: "csc311_lec4_019",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "______ are physical devices such as computers, servers, printers, scanners, and mobile devices used to input, process, store, and output information.",
    options: ["Software", "Hardware", "Procedures", "Networks"],
    correctAnswer: 1,
    explanation:
      "Hardware: Physical devices such as computers, servers, printers, scanners, and mobile devices...",
  },
  {
    id: "csc311_lec4_020",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Programs and applications that control hardware and process data are known as ______.",
    options: ["Procedures", "Hardware", "Software", "Networks"],
    correctAnswer: 2,
    explanation:
      "Software: Programs and applications that control hardware and process data, including operating systems and application software.",
  },
  {
    id: "csc311_lec4_021",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "______ consist of raw facts and figures stored in files or databases that are processed to produce meaningful information.",
    options: ["Data", "Procedures", "Hardware", "Networks"],
    correctAnswer: 0,
    explanation:
      "Data: Raw facts and figures stored in files or databases that are processed to produce meaningful information.",
  },
  {
    id: "csc311_lec4_022",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "______ are rules, guidelines, and methods that govern how data is collected, processed, stored, and used within the system.",
    options: ["Software", "Networks", "Procedures", "Algorithms"],
    correctAnswer: 2,
    explanation:
      "Procedures: Rules, guidelines, and methods that govern how data is collected, processed, stored, and used within the system.",
  },
  {
    id: "csc311_lec4_023",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Communication media and technologies that connect computers and devices are called ______.",
    options: ["Procedures", "Networks", "Software", "Data structures"],
    correctAnswer: 1,
    explanation:
      "Networks: Communication media and technologies that connect computers and devices, enabling data sharing and access to information.",
  },
  {
    id: "csc311_lec4_024",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The ______ perspective views an Information System primarily as a technological solution designed to collect, process, store, and disseminate information efficiently.",
    options: ["socio-technical", "managerial", "technical", "social"],
    correctAnswer: 2,
    explanation:
      "Technical Perspective of Information Systems: The technical perspective views an Information System primarily as a technological solution...",
  },
  {
    id: "csc311_lec4_025",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "In the technical perspective, system performance is NOT measured by user acceptance, but rather by speed, accuracy, reliability, security, and efficiency.",
    options: ["Maybe", "I don't know", "True", "False"],
    correctAnswer: 2,
    explanation:
      "True. From this view, system performance is measured in terms of speed, accuracy, reliability, security, and efficiency.",
  },
  {
    id: "csc311_lec4_026",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The technical perspective of Information Systems is rooted in computer science, engineering, and ______.",
    options: ["psychology", "mathematics", "sociology", "anthropology"],
    correctAnswer: 1,
    explanation:
      "This perspective is rooted in computer science, engineering, and mathematics.",
  },
  {
    id: "csc311_lec4_027",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The ______ perspective focuses on how people interact with, interpret, and use information, and how IS influences work practices and power relations.",
    options: ["technical", "algorithmic", "social", "mathematical"],
    correctAnswer: 2,
    explanation:
      "Social Perspective of Information Systems: The social perspective focuses on the human, organisational, and societal aspects of Information Systems. It emphasizes how people interact with, interpret, and use information...",
  },
  {
    id: "csc311_lec4_028",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "From the social viewpoint, an Information System is not just a technical artifact but a ______ construct.",
    options: ["mathematical", "social", "hardware", "bureaucratic"],
    correctAnswer: 1,
    explanation:
      "From this viewpoint, an Information System is not just a technical artifact but a social construct shaped by users’ values, skills, attitudes...",
  },
  {
    id: "csc311_lec4_029",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "According to the social perspective, the success or failure of an IS is linked to user acceptance, organisational culture, management support, and ______ considerations.",
    options: [
      "processing speed",
      "ethical",
      "hardware capability",
      "network bandwidth",
    ],
    correctAnswer: 1,
    explanation:
      "Success or failure of an IS is therefore linked to user acceptance, organisational culture, management support, training, and ethical considerations, rather than technology alone.",
  },
  {
    id: "csc311_lec4_030",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The ______ perspective integrates both the technical and social dimensions, arguing they must be jointly optimized.",
    options: [
      "socio-technical",
      "scientific",
      "mathematical",
      "hardware-first",
    ],
    correctAnswer: 0,
    explanation:
      "Socio-Technical Perspective of Information Systems: The socio-technical perspective integrates both the technical and social dimensions, arguing that Information Systems are composed of interdependent social and technical subsystems that must be jointly optimized.",
  },
  {
    id: "csc311_lec4_031",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The socio-technical perspective argues that system success depends on achieving a balance between technical efficiency and social ______.",
    options: ["hierarchy", "dominance", "isolation", "effectiveness"],
    correctAnswer: 3,
    explanation:
      "Therefore, system success depends on achieving a balance between technical efficiency and social effectiveness.",
  },
  {
    id: "csc311_lec4_032",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Operational staff users of Information Systems typically include clerks, technicians, and ______.",
    options: [
      "senior management",
      "frontline workers",
      "strategic decision-makers",
      "external regulators",
    ],
    correctAnswer: 1,
    explanation:
      "Users of Information Systems? Operational staff – clerks, technicians, frontline workers.",
  },
  {
    id: "csc311_lec4_033",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "______ are the users of Information Systems who act as strategic decision-makers.",
    options: ["Executives", "Clerks", "System developers", "Suppliers"],
    correctAnswer: 0,
    explanation: "Executives – strategic decision-makers.",
  },
  {
    id: "csc311_lec4_034",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "IT professionals who use Information Systems include system developers and ______.",
    options: ["customers", "regulators", "administrators", "clerks"],
    correctAnswer: 2,
    explanation: "IT professionals – system developers and administrators.",
  },
  {
    id: "csc311_lec4_035",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Customers, suppliers, and regulators are considered ______ users of Information Systems.",
    options: ["internal", "external", "operational", "executive"],
    correctAnswer: 1,
    explanation: "External users – customers, suppliers, regulators.",
  },
  {
    id: "csc311_lec4_036",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "One way Information Systems are used is to process daily ______ such as payroll and sales.",
    options: ["algorithms", "transactions", "ethics", "innovations"],
    correctAnswer: 1,
    explanation:
      "How Information Systems Are Used? Processing daily transactions (e.g., payroll, sales).",
  },
  {
    id: "csc311_lec4_037",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Information Systems deliver better decision-making capabilities through ______ information.",
    options: ["delayed", "timely", "obsolete", "unprocessed"],
    correctAnswer: 1,
    explanation:
      "Benefits Delivered by Information Systems: Better decision-making through timely information.",
  },
  {
    id: "csc311_lec4_038",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Information Systems are known to help organizations achieve a competitive ______.",
    options: ["disadvantage", "isolation", "equilibrium", "advantage"],
    correctAnswer: 3,
    explanation:
      "Benefits Delivered by Information Systems: Competitive advantage and innovation.",
  },
  {
    id: "csc311_lec4_039",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The ______ principle states that IS must align with organisational goals.",
    options: [
      "Data quality",
      "Socio-technical",
      "Alignment",
      "System integration",
    ],
    correctAnswer: 2,
    explanation:
      "Alignment principle: IS must align with organisational goals.",
  },
  {
    id: "csc311_lec4_040",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The Socio-technical principle states that IS involves both technology and people.",
    options: ["I don't know", "True", "False", "Maybe"],
    correctAnswer: 1,
    explanation:
      "True. Socio-technical principle: IS involves both technology and people.",
  },
  {
    id: "csc311_lec4_041",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The ______ principle emphasizes that accurate, timely, and relevant data is essential.",
    options: [
      "Data quality",
      "System integration",
      "User-centred design",
      "Alignment",
    ],
    correctAnswer: 0,
    explanation:
      "Data quality principle: Accurate, timely, and relevant data is essential.",
  },
  {
    id: "csc311_lec4_042",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The System integration principle dictates that IS components must ______.",
    options: [
      "be entirely automated",
      "operate independently",
      "work together",
      "ignore human factors",
    ],
    correctAnswer: 2,
    explanation:
      "System integration principle: IS components must work together.",
  },
  {
    id: "csc311_lec4_043",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The User-centred design principle asserts that systems should meet ______.",
    options: [
      "user needs",
      "hardware limitations",
      "legacy requirements",
      "theoretical ideals",
    ],
    correctAnswer: 0,
    explanation:
      "User-centred design principle: Systems should meet user needs.",
  },
  {
    id: "csc311_lec4_044",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "According to the Socio-Technical Principle, ignoring the human and social aspects often leads to system ______.",
    options: ["upgrades", "success", "failure", "innovation"],
    correctAnswer: 2,
    explanation:
      "Ignoring the human and social aspects often leads to system failure.",
  },
  {
    id: "csc311_lec4_045",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "According to the Organisational Alignment Principle, systems that do not align with business objectives often become ______ or abandoned.",
    options: [
      "underutilised",
      "highly profitable",
      "industry standards",
      "fully integrated",
    ],
    correctAnswer: 0,
    explanation:
      "Systems that do not align with business objectives often become underutilised or abandoned.",
  },
  {
    id: "csc311_lec4_046",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Information is considered a valuable organisational resource, similar to capital, labour, and ______.",
    options: ["materials", "liabilities", "debts", "expenses"],
    correctAnswer: 0,
    explanation:
      "Information is a valuable organisational resource, similar to capital, labour, and materials.",
  },
  {
    id: "csc311_lec4_047",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The value of an information system depends heavily on the ______ of data it processes.",
    options: ["quality", "quantity", "color", "storage medium"],
    correctAnswer: 0,
    explanation:
      "The value of an information system depends on the quality of data it processes.",
  },
  {
    id: "csc311_lec4_048",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Poor data quality leads to incorrect information and poor ______.",
    options: ["decisions", "networks", "hardware", "programming"],
    correctAnswer: 0,
    explanation:
      "Poor data quality leads to incorrect information and poor decisions.",
  },
  {
    id: "csc311_lec4_049",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "IS must ensure data accuracy, completeness, consistency, ______, and security.",
    options: ["timeliness", "redundancy", "obsolescence", "opacity"],
    correctAnswer: 0,
    explanation:
      "IS must therefore ensure data accuracy, completeness, consistency, timeliness, and security.",
  },
  {
    id: "csc311_lec4_050",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "User involvement during system development increases acceptance, usability, and ______.",
    options: ["complexity", "resistance", "effectiveness", "obsolescence"],
    correctAnswer: 2,
    explanation:
      "User involvement during system development increases acceptance, usability, and effectiveness.",
  },
  {
    id: "csc311_lec4_051",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Systems that are complex or difficult to use reduce productivity and may be ______ by users.",
    options: ["embraced", "resisted", "celebrated", "purchased"],
    correctAnswer: 1,
    explanation:
      "Systems that are complex or difficult to use reduce productivity and may be resisted by users.",
  },
  {
    id: "csc311_lec4_052",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Modern organisations require integration across departments so that information flows seamlessly, avoiding duplication, inconsistency, and ______.",
    options: ["inefficiency", "innovation", "security", "alignment"],
    correctAnswer: 0,
    explanation:
      "In addition, modern organisations require integration across departments so that information flows seamlessly, avoiding duplication, inconsistency, and inefficiency.",
  },
  {
    id: "csc311_lec4_053",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "A key assumption about IS is that ______ alone cannot solve organisational problems.",
    options: ["Technology", "Management", "Information", "Data"],
    correctAnswer: 0,
    explanation:
      "Key Assumptions: Technology alone cannot solve organisational problems.",
  },
  {
    id: "csc311_lec4_054",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "One key assumption is that users influence the success or failure of IS.",
    options: ["Maybe", "I don't know", "True", "False"],
    correctAnswer: 2,
    explanation:
      "True. Key Assumptions: Users influence the success or failure of IS.",
  },
  {
    id: "csc311_lec4_055",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "A key assumption is that the organisational context has no effect on IS design and use.",
    options: ["Maybe", "False", "I don't know", "True"],
    correctAnswer: 1,
    explanation:
      "False. The correct assumption is: Organisational context affects IS design and use.",
  },
  {
    id: "csc311_lec4_056",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "A key assumption is that Information Systems evolve with changes in the ______ environment.",
    options: ["business", "biological", "astronomical", "geological"],
    correctAnswer: 0,
    explanation:
      "Key Assumptions: IS evolves with changes in business environment.",
  },
  {
    id: "csc311_lec4_057",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "In the banking sector, Core banking systems integrate customer data, transactions, and reporting to support efficiency and regulatory ______.",
    options: ["complexity", "avoidance", "compliance", "resistance"],
    correctAnswer: 2,
    explanation:
      "Practical Application: Banking sector: Core banking systems integrate customer data, transactions, and reporting to support efficiency and regulatory compliance.",
  },
  {
    id: "csc311_lec4_058",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "In Universities, ______ Information Systems are used to manage admissions, registration, results, and records.",
    options: ["Patient", "Student", "Core Banking", "Retail"],
    correctAnswer: 1,
    explanation:
      "Universities: Student Information Systems manage admissions, registration, results, and records.",
  },
  {
    id: "csc311_lec4_059",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "In Hospitals, ______ Information Systems support patient records, diagnosis, and treatment.",
    options: ["Health", "Financial", "Educational", "Retail"],
    correctAnswer: 0,
    explanation:
      "Hospitals: Health Information Systems support patient records, diagnosis, and treatment.",
  },
  {
    id: "csc311_lec4_060",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "In retail organisations, ______ systems track sales, inventory, and customer behaviour.",
    options: [
      "Core banking",
      "Health Information",
      "Point-of-Sale (POS)",
      "E-government",
    ],
    correctAnswer: 2,
    explanation:
      "Retail organisations: Point-of-Sale (POS) systems track sales, inventory, and customer behaviour.",
  },
  {
    id: "csc311_lec4_061",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "In government agencies, E-government systems improve transparency, service delivery, and record ______.",
    options: ["destruction", "obsolescence", "management", "encryption"],
    correctAnswer: 2,
    explanation:
      "Government agencies: E-government systems improve transparency, service delivery, and record management.",
  },
  {
    id: "csc311_lec4_062",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The practical application of IS principles in real organisations demonstrates alignment with organisational goals, user involvement, data accuracy, and integration of technology with ______.",
    options: [
      "work processes",
      "theoretical models",
      "legacy hardware",
      "unrelated departments",
    ],
    correctAnswer: 0,
    explanation:
      "These systems demonstrate alignment with organisational goals, user involvement, data accuracy, and integration of technology with work processes.",
  },
  {
    id: "csc311_lec4_063",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "One of the emerging consequences for organisations is an increased ______ on information systems.",
    options: ["independence", "dependence", "ignorance", "distrust"],
    correctAnswer: 1,
    explanation:
      "Emerging Consequences for Organisations: Increased dependence on information systems.",
  },
  {
    id: "csc311_lec4_064",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "An emerging consequence for organisations is the shift toward ______ decision-making.",
    options: ["intuition-driven", "data-driven", "guesswork", "emotion-driven"],
    correctAnswer: 1,
    explanation: "Shift toward data-driven decision-making.",
  },
  {
    id: "csc311_lec4_065",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Information systems have led to greater organisational flexibility and ______ work.",
    options: ["remote", "rigid", "manual", "inefficient"],
    correctAnswer: 0,
    explanation: "Greater organisational flexibility and remote work.",
  },
  {
    id: "csc311_lec4_066",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "With the rise of modern Information Systems, organisations face new security and ______ challenges.",
    options: ["cybersecurity", "punch card", "manual filing", "mainframe"],
    correctAnswer: 0,
    explanation: "New security and cybersecurity challenges.",
  },
  {
    id: "csc311_lec4_067",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "There are emerging ethical and governance issues in ______ systems.",
    options: ["AI-driven", "paper-based", "manual", "abacus"],
    correctAnswer: 0,
    explanation: "Ethical and governance issues in AI-driven systems.",
  },
  {
    id: "csc311_lec4_068",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "Because of emerging consequences, there is a continuous need for system evaluation and ______.",
    options: ["innovation", "abandonment", "stagnation", "deprecation"],
    correctAnswer: 0,
    explanation: "Continuous need for system evaluation and innovation.",
  },
  {
    id: "csc311_lec4_069",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The concept that Information Systems are not purely technical but involve social structures is known as the Socio-Technical Principle.",
    options: ["True", "I don't know", "Maybe", "False"],
    correctAnswer: 0,
    explanation:
      "True. Information systems are not purely technical systems; they are socio-technical systems that combine technology with people, organisational structures, and work practices.",
  },
  {
    id: "csc311_lec4_070",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The Data processing era (1950s–1960s) primarily used ______.",
    options: [
      "Cloud computing",
      "Mobile systems",
      "Mainframe computers",
      "Artificial Intelligence",
    ],
    correctAnswer: 2,
    explanation:
      "Data processing era (1950s–1960s) – mainframe computers for payroll and accounting.",
  },
  {
    id: "csc311_lec4_071",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "During the 1990s, Enterprise Systems focused on integrating ERP, CRM, and ______.",
    options: ["AI", "SCM", "LAN", "WAN"],
    correctAnswer: 1,
    explanation: "Enterprise Systems (1990s) – ERP, CRM, SCM integration.",
  },
  {
    id: "csc311_lec4_072",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The social perspective of IS focuses on how IS influences work practices, power relations, communication patterns, ______, and decision-making.",
    options: [
      "culture",
      "hardware speed",
      "algorithmic efficiency",
      "database normalization",
    ],
    correctAnswer: 0,
    explanation:
      "It emphasizes how people interact with, interpret, and use information, and how IS influences work practices, power relations, communication patterns, culture, and decision-making.",
  },
  {
    id: "csc311_lec4_073",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "In the 2000s, Wide Area Networks expanded to the Internet to include global enterprise and business ______.",
    options: ["partners", "tabulators", "punch cards", "calculators"],
    correctAnswer: 0,
    explanation:
      "Jan 1, 2000: Wide Area Network. Wide Area Networks expands to the Internet to include global enterprise and business partners.",
  },
  {
    id: "csc311_lec4_074",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "The main focus in the year 2000 was efficiencies and speed in inventory, manufacturing, and ______.",
    options: [
      "distributions",
      "paper records",
      "mechanical calculation",
      "census tabulation",
    ],
    correctAnswer: 0,
    explanation:
      "Main focus was efficiencies and speed in inventory, manufacturing and distributions.",
  },
  {
    id: "csc311_lec4_075",
    course: "CSC 311",
    chapter: "Chapter 4_1",
    text: "One of the learning outcomes is to explain the fundamental principles and ______ of studying the application of information systems.",
    options: [
      "hardware specifications",
      "assumptions",
      "network topologies",
      "cloud architectures",
    ],
    correctAnswer: 1,
    explanation:
      "Learning outcomes: explain the fundamental principles and assumptions of studying the application of information system.",
  },
];
export default csc311Chapter4_1;
